import { useMemo } from 'react';
import { KpiWithValues, KpiCategory, KpiValueSource, calculateRagStatus } from '../types';
import { subDays, format, subHours } from 'date-fns';

// Mock users for attribution
const MOCK_USERS = {
  'user-1': { id: 'user-1', display_name: 'Maria Silva', photo_url: null },
  'user-2': { id: 'user-2', display_name: 'João Costa', photo_url: null },
  'user-3': { id: 'user-3', display_name: 'Ana Rodrigues', photo_url: null },
  'user-4': { id: 'user-4', display_name: 'Carlos Lima', photo_url: null },
  'user-5': { id: 'user-5', display_name: 'Pedro Santos', photo_url: null },
  'user-6': { id: 'user-6', display_name: 'Fernanda Oliveira', photo_url: null },
  'user-7': { id: 'user-7', display_name: 'Lucia Mendes', photo_url: null },
};

// Generate realistic historical values with user attribution
function generateHistory(
  baseValue: number,
  days: number,
  volatility: number = 0.05,
  trend: 'up' | 'down' | 'stable' = 'stable',
  source: KpiValueSource = 'api',
  createdBy: string | null = null
): { value: number; date: string; created_at: string; source: KpiValueSource; created_by: string | null }[] {
  const history: { value: number; date: string; created_at: string; source: KpiValueSource; created_by: string | null }[] = [];
  let currentValue = baseValue * (1 - (days * 0.01 * (trend === 'up' ? -1 : trend === 'down' ? 1 : 0)));

  for (let i = days; i >= 0; i--) {
    const variation = (Math.random() - 0.5) * 2 * volatility * currentValue;
    const trendFactor = trend === 'up' ? 1.002 : trend === 'down' ? 0.998 : 1;
    currentValue = Math.max(0, currentValue * trendFactor + variation);
    
    const referenceDate = subDays(new Date(), i);
    const createdAtDate = subHours(referenceDate, Math.floor(Math.random() * 4) + 8); // 8-12 hours after reference
    
    history.push({
      value: Math.round(currentValue * 100) / 100,
      date: format(referenceDate, 'yyyy-MM-dd'),
      created_at: createdAtDate.toISOString(),
      source,
      created_by: source === 'manual' ? createdBy : null,
    });
  }

  return history;
}

// Mock KPI data with realistic values
export function useMockKpiData() {
  const mockKpis = useMemo<KpiWithValues[]>(() => {
    const buId = 'mock-bu-id';
    const now = new Date();
    
    const kpisData: Array<Omit<KpiWithValues, 'rag_status'>> = [
      // Financeiro - MRR (API)
      {
        id: 'kpi-mrr',
        name: 'MRR',
        description: 'Receita Recorrente Mensal',
        category: 'financeiro' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-1',
        team_id: 'team-financeiro',
        unit: 'R$',
        direction: 'up',
        frequency: 'monthly',
        target_value: 1500000,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/billing/mrr', method: 'GET' },
        visibility: 'bu',
        comparison_rule: 'higher_is_better',
        linked_okrs: ['okr-1', 'okr-2'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-1'],
        team: { id: 'team-financeiro', name: 'Financeiro' },
        values: generateHistory(1180000, 30, 0.02, 'up', 'api').map((h, i) => ({
          id: `val-mrr-${i}`,
          kpi_id: 'kpi-mrr',
          value: h.value,
          reference_date: h.date,
          source: h.source,
          notes: null,
          created_by: h.created_by,
          created_at: h.created_at,
        })),
        current_value: 1180000,
        previous_value: 1150000,
        variation: 2.6,
        trend: 'up',
        last_updated_at: subHours(now, 2).toISOString(),
        last_update_source: 'api',
        last_updated_by: null,
        last_updated_by_user: null,
      },
      // Financeiro - NRR (API)
      {
        id: 'kpi-nrr',
        name: 'NRR',
        description: 'Net Revenue Retention - Retenção Líquida de Receita',
        category: 'financeiro' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-2',
        team_id: 'team-cs',
        unit: '%',
        direction: 'up',
        frequency: 'monthly',
        target_value: 105,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/metrics/nrr' },
        visibility: 'bu',
        comparison_rule: 'higher_is_better',
        linked_okrs: ['okr-3'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-2'],
        team: { id: 'team-cs', name: 'Customer Success' },
        values: generateHistory(99, 12, 0.01, 'stable', 'api').map((h, i) => ({
          id: `val-nrr-${i}`,
          kpi_id: 'kpi-nrr',
          value: h.value,
          reference_date: h.date,
          source: h.source,
          notes: null,
          created_by: h.created_by,
          created_at: h.created_at,
        })),
        current_value: 99,
        previous_value: 98.5,
        variation: 0.5,
        trend: 'up',
        last_updated_at: subHours(now, 6).toISOString(),
        last_update_source: 'api',
        last_updated_by: null,
        last_updated_by_user: null,
      },
      // Financeiro - EBITDA (Planilha)
      {
        id: 'kpi-ebitda',
        name: 'EBITDA',
        description: 'Lucros antes de juros, impostos, depreciação e amortização',
        category: 'financeiro' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-1',
        team_id: 'team-financeiro',
        unit: 'R$',
        direction: 'up',
        frequency: 'monthly',
        target_value: 350000,
        status: 'active',
        source_type: 'spreadsheet',
        source_config: { sheetId: 'abc123', cell: 'B15', sheetName: 'Financeiro' },
        visibility: 'restricted',
        comparison_rule: 'higher_is_better',
        linked_okrs: [],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-1'],
        team: { id: 'team-financeiro', name: 'Financeiro' },
        values: generateHistory(280000, 12, 0.05, 'up', 'spreadsheet').map((h, i) => ({
          id: `val-ebitda-${i}`,
          kpi_id: 'kpi-ebitda',
          value: h.value,
          reference_date: h.date,
          source: h.source,
          notes: null,
          created_by: h.created_by,
          created_at: h.created_at,
        })),
        current_value: 285000,
        previous_value: 270000,
        variation: 5.5,
        trend: 'up',
        last_updated_at: subDays(now, 1).toISOString(),
        last_update_source: 'spreadsheet',
        last_updated_by: null,
        last_updated_by_user: null,
      },
      // Growth - Leads (API)
      {
        id: 'kpi-leads',
        name: 'Leads Qualificados',
        description: 'Total de leads qualificados no mês',
        category: 'growth' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-3',
        team_id: 'team-marketing',
        unit: 'número',
        direction: 'up',
        frequency: 'weekly',
        target_value: 500,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/crm/leads', method: 'GET' },
        visibility: 'bu',
        comparison_rule: 'higher_is_better',
        linked_okrs: ['okr-4'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-3'],
        team: { id: 'team-marketing', name: 'Marketing' },
        values: generateHistory(420, 8, 0.08, 'up', 'api').map((h, i) => ({
          id: `val-leads-${i}`,
          kpi_id: 'kpi-leads',
          value: Math.round(h.value),
          reference_date: h.date,
          source: h.source,
          notes: null,
          created_by: h.created_by,
          created_at: h.created_at,
        })),
        current_value: 456,
        previous_value: 420,
        variation: 8.6,
        trend: 'up',
        last_updated_at: subHours(now, 1).toISOString(),
        last_update_source: 'api',
        last_updated_by: null,
        last_updated_by_user: null,
      },
      // Growth - Taxa Conversão (API com falha simulada)
      {
        id: 'kpi-conversion',
        name: 'Taxa de Conversão',
        description: 'Conversão de trial para cliente',
        category: 'growth' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-3',
        team_id: 'team-vendas',
        unit: '%',
        direction: 'up',
        frequency: 'weekly',
        target_value: 25,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/sales/conversion' },
        visibility: 'bu',
        comparison_rule: 'higher_is_better',
        linked_okrs: ['okr-4', 'okr-5'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-3'],
        team: { id: 'team-vendas', name: 'Vendas' },
        values: generateHistory(18, 8, 0.05, 'down', 'api').map((h, i) => ({
          id: `val-conv-${i}`,
          kpi_id: 'kpi-conversion',
          value: Math.round(h.value * 10) / 10,
          reference_date: h.date,
          source: h.source,
          notes: null,
          created_by: h.created_by,
          created_at: h.created_at,
        })),
        current_value: 16.5,
        previous_value: 18.2,
        variation: -9.3,
        trend: 'down',
        last_updated_at: subDays(now, 3).toISOString(),
        last_update_source: 'api',
        last_updated_by: null,
        last_updated_by_user: null,
        last_update_failed: true, // Simulando falha de integração
      },
      // CS - NPS (Webhook)
      {
        id: 'kpi-nps',
        name: 'NPS',
        description: 'Net Promoter Score',
        category: 'cs' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-2',
        team_id: 'team-cs',
        unit: 'score',
        direction: 'up',
        frequency: 'monthly',
        target_value: 70,
        status: 'active',
        source_type: 'webhook',
        source_config: { webhookId: 'wh-nps-123', endpoint: 'https://hub.jetimob.com/webhooks/kpi/nps' },
        visibility: 'bu',
        comparison_rule: 'higher_is_better',
        linked_okrs: ['okr-3'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-2'],
        team: { id: 'team-cs', name: 'Customer Success' },
        values: generateHistory(56, 12, 0.03, 'up', 'webhook').map((h, i) => ({
          id: `val-nps-${i}`,
          kpi_id: 'kpi-nps',
          value: Math.round(h.value),
          reference_date: h.date,
          source: h.source,
          notes: null,
          created_by: h.created_by,
          created_at: h.created_at,
        })),
        current_value: 56,
        previous_value: 54,
        variation: 3.7,
        trend: 'up',
        last_updated_at: subHours(now, 12).toISOString(),
        last_update_source: 'webhook',
        last_updated_by: null,
        last_updated_by_user: null,
      },
      // CS - Churn (API)
      {
        id: 'kpi-churn',
        name: 'Churn Rate',
        description: 'Taxa de cancelamento mensal',
        category: 'cs' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-2',
        team_id: 'team-cs',
        unit: '%',
        direction: 'down',
        frequency: 'monthly',
        target_value: 2,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/metrics/churn' },
        visibility: 'bu',
        comparison_rule: 'lower_is_better',
        linked_okrs: ['okr-3'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-2'],
        team: { id: 'team-cs', name: 'Customer Success' },
        values: generateHistory(3.2, 12, 0.1, 'down', 'api').map((h, i) => ({
          id: `val-churn-${i}`,
          kpi_id: 'kpi-churn',
          value: Math.round(h.value * 10) / 10,
          reference_date: h.date,
          source: h.source,
          notes: null,
          created_by: h.created_by,
          created_at: h.created_at,
        })),
        current_value: 2.8,
        previous_value: 3.1,
        variation: -9.7,
        trend: 'down',
        last_updated_at: subHours(now, 4).toISOString(),
        last_update_source: 'api',
        last_updated_by: null,
        last_updated_by_user: null,
      },
      // Produto - DAU (Database)
      {
        id: 'kpi-dau',
        name: 'DAU',
        description: 'Daily Active Users',
        category: 'produto' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-4',
        team_id: 'team-produto',
        unit: 'número',
        direction: 'up',
        frequency: 'daily',
        target_value: 5000,
        status: 'active',
        source_type: 'database',
        source_config: { query: 'SELECT COUNT(*) FROM active_users WHERE date = CURRENT_DATE' },
        visibility: 'team',
        comparison_rule: 'higher_is_better',
        linked_okrs: ['okr-6'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-4'],
        team: { id: 'team-produto', name: 'Produto' },
        values: generateHistory(4200, 30, 0.03, 'up', 'database').map((h, i) => ({
          id: `val-dau-${i}`,
          kpi_id: 'kpi-dau',
          value: Math.round(h.value),
          reference_date: h.date,
          source: h.source,
          notes: null,
          created_by: h.created_by,
          created_at: h.created_at,
        })),
        current_value: 4350,
        previous_value: 4200,
        variation: 3.6,
        trend: 'up',
        last_updated_at: subHours(now, 1).toISOString(),
        last_update_source: 'database',
        last_updated_by: null,
        last_updated_by_user: null,
      },
      // Produto - Adoção Features (Manual)
      {
        id: 'kpi-feature-adoption',
        name: 'Adoção de Features',
        description: 'Percentual de usuários usando novas features',
        category: 'produto' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-4',
        team_id: 'team-produto',
        unit: '%',
        direction: 'up',
        frequency: 'weekly',
        target_value: 60,
        status: 'active',
        source_type: 'manual',
        source_config: null,
        visibility: 'team',
        comparison_rule: 'higher_is_better',
        linked_okrs: [],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-4'],
        team: { id: 'team-produto', name: 'Produto' },
        values: generateHistory(42, 8, 0.04, 'up', 'manual', 'user-4').map((h, i) => ({
          id: `val-feature-${i}`,
          kpi_id: 'kpi-feature-adoption',
          value: Math.round(h.value),
          reference_date: h.date,
          source: h.source,
          notes: i === 0 ? 'Atualização após lançamento do novo dashboard' : null,
          created_by: h.created_by,
          created_at: h.created_at,
          created_by_user: MOCK_USERS['user-4'],
        })),
        current_value: 45,
        previous_value: 42,
        variation: 7.1,
        trend: 'up',
        last_updated_at: subHours(now, 18).toISOString(),
        last_update_source: 'manual',
        last_updated_by: 'user-4',
        last_updated_by_user: MOCK_USERS['user-4'],
      },
      // Operações - Uptime (API)
      {
        id: 'kpi-uptime',
        name: 'Uptime',
        description: 'Disponibilidade do sistema',
        category: 'operacoes' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-5',
        team_id: 'team-infra',
        unit: '%',
        direction: 'up',
        frequency: 'daily',
        target_value: 99.9,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/monitoring/uptime' },
        visibility: 'bu',
        comparison_rule: 'higher_is_better',
        linked_okrs: [],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-5'],
        team: { id: 'team-infra', name: 'Infraestrutura' },
        values: generateHistory(99.85, 30, 0.001, 'stable', 'api').map((h, i) => ({
          id: `val-uptime-${i}`,
          kpi_id: 'kpi-uptime',
          value: Math.min(100, Math.round(h.value * 100) / 100),
          reference_date: h.date,
          source: h.source,
          notes: null,
          created_by: h.created_by,
          created_at: h.created_at,
        })),
        current_value: 99.87,
        previous_value: 99.82,
        variation: 0.05,
        trend: 'up',
        last_updated_at: subHours(now, 0.5).toISOString(),
        last_update_source: 'api',
        last_updated_by: null,
        last_updated_by_user: null,
      },
      // Operações - Tempo Resolução (API)
      {
        id: 'kpi-ticket-resolution',
        name: 'Tempo Médio de Resolução',
        description: 'Tempo médio para resolver tickets de suporte',
        category: 'operacoes' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-6',
        team_id: 'team-suporte',
        unit: 'horas',
        direction: 'down',
        frequency: 'weekly',
        target_value: 4,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/support/resolution-time' },
        visibility: 'team',
        comparison_rule: 'lower_is_better',
        linked_okrs: ['okr-7'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-6'],
        team: { id: 'team-suporte', name: 'Suporte' },
        values: generateHistory(6.5, 8, 0.08, 'down', 'api').map((h, i) => ({
          id: `val-ticket-${i}`,
          kpi_id: 'kpi-ticket-resolution',
          value: Math.round(h.value * 10) / 10,
          reference_date: h.date,
          source: h.source,
          notes: null,
          created_by: h.created_by,
          created_at: h.created_at,
        })),
        current_value: 5.8,
        previous_value: 6.2,
        variation: -6.5,
        trend: 'down',
        last_updated_at: subHours(now, 3).toISOString(),
        last_update_source: 'api',
        last_updated_by: null,
        last_updated_by_user: null,
      },
      // Pessoas - eNPS (Manual)
      {
        id: 'kpi-enps',
        name: 'eNPS',
        description: 'Employee Net Promoter Score',
        category: 'pessoas' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-7',
        team_id: 'team-rh',
        unit: 'score',
        direction: 'up',
        frequency: 'quarterly',
        target_value: 50,
        status: 'active',
        source_type: 'manual',
        source_config: null,
        visibility: 'restricted',
        comparison_rule: 'higher_is_better',
        linked_okrs: [],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-7'],
        team: { id: 'team-rh', name: 'RH' },
        values: [
          { id: 'val-enps-1', kpi_id: 'kpi-enps', value: 42, reference_date: '2024-03-31', source: 'manual' as const, notes: 'Q1 2024', created_by: 'user-7', created_at: '2024-04-01T09:00:00Z', created_by_user: MOCK_USERS['user-7'] },
          { id: 'val-enps-2', kpi_id: 'kpi-enps', value: 45, reference_date: '2024-06-30', source: 'manual' as const, notes: 'Q2 2024', created_by: 'user-7', created_at: '2024-07-01T10:30:00Z', created_by_user: MOCK_USERS['user-7'] },
          { id: 'val-enps-3', kpi_id: 'kpi-enps', value: 48, reference_date: '2024-09-30', source: 'manual' as const, notes: 'Q3 2024 - Melhoria após ajustes no plano de carreira', created_by: 'user-7', created_at: '2024-10-02T14:15:00Z', created_by_user: MOCK_USERS['user-7'] },
        ],
        current_value: 48,
        previous_value: 45,
        variation: 6.7,
        trend: 'up',
        last_updated_at: '2024-10-02T14:15:00Z',
        last_update_source: 'manual',
        last_updated_by: 'user-7',
        last_updated_by_user: MOCK_USERS['user-7'],
      },
      // Pessoas - Turnover (Manual)
      {
        id: 'kpi-turnover',
        name: 'Turnover Voluntário',
        description: 'Taxa de saída voluntária de colaboradores',
        category: 'pessoas' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-7',
        team_id: 'team-rh',
        unit: '%',
        direction: 'down',
        frequency: 'monthly',
        target_value: 5,
        status: 'active',
        source_type: 'manual',
        source_config: null,
        visibility: 'restricted',
        comparison_rule: 'lower_is_better',
        linked_okrs: [],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: MOCK_USERS['user-7'],
        team: { id: 'team-rh', name: 'RH' },
        values: generateHistory(8, 12, 0.1, 'down', 'manual', 'user-7').map((h, i) => ({
          id: `val-turnover-${i}`,
          kpi_id: 'kpi-turnover',
          value: Math.round(h.value * 10) / 10,
          reference_date: h.date,
          source: h.source,
          notes: null,
          created_by: h.created_by,
          created_at: h.created_at,
          created_by_user: MOCK_USERS['user-7'],
        })),
        current_value: 7.2,
        previous_value: 7.8,
        variation: -7.7,
        trend: 'down',
        last_updated_at: subDays(now, 2).toISOString(),
        last_update_source: 'manual',
        last_updated_by: 'user-7',
        last_updated_by_user: MOCK_USERS['user-7'],
      },
    ];

    // Calculate RAG status for each KPI
    return kpisData.map(kpi => ({
      ...kpi,
      rag_status: calculateRagStatus(kpi.current_value, kpi.target_value, kpi.direction),
    }));
  }, []);

  // Summary stats
  const summary = useMemo(() => {
    const total = mockKpis.length;
    const onTrack = mockKpis.filter(k => k.rag_status === 'on_track').length;
    const atRisk = mockKpis.filter(k => k.rag_status === 'at_risk').length;
    const offTrack = mockKpis.filter(k => k.rag_status === 'off_track').length;
    const noData = mockKpis.filter(k => k.rag_status === 'no_data').length;
    const improving = mockKpis.filter(k => 
      (k.direction === 'up' && k.trend === 'up') ||
      (k.direction === 'down' && k.trend === 'down')
    ).length;

    return { total, onTrack, atRisk, offTrack, noData, improving };
  }, [mockKpis]);

  return {
    kpis: mockKpis,
    summary,
    isLoading: false,
  };
}
