import { useMemo } from 'react';
import { KpiWithValues, KpiCategory, calculateRagStatus } from '../types';
import { subDays, format } from 'date-fns';

// Generate realistic historical values
function generateHistory(
  baseValue: number,
  days: number,
  volatility: number = 0.05,
  trend: 'up' | 'down' | 'stable' = 'stable'
): { value: number; date: string }[] {
  const history: { value: number; date: string }[] = [];
  let currentValue = baseValue * (1 - (days * 0.01 * (trend === 'up' ? -1 : trend === 'down' ? 1 : 0)));

  for (let i = days; i >= 0; i--) {
    const variation = (Math.random() - 0.5) * 2 * volatility * currentValue;
    const trendFactor = trend === 'up' ? 1.002 : trend === 'down' ? 0.998 : 1;
    currentValue = Math.max(0, currentValue * trendFactor + variation);
    
    history.push({
      value: Math.round(currentValue * 100) / 100,
      date: format(subDays(new Date(), i), 'yyyy-MM-dd'),
    });
  }

  return history;
}

// Mock KPI data with realistic values
export function useMockKpiData() {
  const mockKpis = useMemo<KpiWithValues[]>(() => {
    const buId = 'mock-bu-id';
    
    const kpisData: Omit<KpiWithValues, 'rag_status'>[] = [
      // Financeiro
      {
        id: 'kpi-mrr',
        name: 'MRR',
        description: 'Receita Recorrente Mensal',
        category: 'financeiro' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-1',
        team_id: 'team-financeiro',
        unit: 'R$',
        direction: 'up',
        frequency: 'monthly',
        target_value: 1500000,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/billing/mrr' },
        visibility: 'bu',
        linked_okrs: ['okr-1', 'okr-2'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-1', display_name: 'Maria Silva', photo_url: null },
        team: { id: 'team-financeiro', name: 'Financeiro' },
        values: generateHistory(1180000, 30, 0.02, 'up').map((h, i) => ({
          id: `val-mrr-${i}`,
          kpi_id: 'kpi-mrr',
          value: h.value,
          reference_date: h.date,
          source: 'api' as const,
          notes: null,
          created_by: null,
          created_at: h.date,
        })),
        current_value: 1180000,
        previous_value: 1150000,
        variation: 2.6,
        trend: 'up',
      },
      {
        id: 'kpi-nrr',
        name: 'NRR',
        description: 'Net Revenue Retention - Retenção Líquida de Receita',
        category: 'financeiro' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-2',
        team_id: 'team-cs',
        unit: '%',
        direction: 'up',
        frequency: 'monthly',
        target_value: 105,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/metrics/nrr' },
        visibility: 'bu',
        linked_okrs: ['okr-3'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-2', display_name: 'João Costa', photo_url: null },
        team: { id: 'team-cs', name: 'Customer Success' },
        values: generateHistory(99, 12, 0.01, 'stable').map((h, i) => ({
          id: `val-nrr-${i}`,
          kpi_id: 'kpi-nrr',
          value: h.value,
          reference_date: h.date,
          source: 'api' as const,
          notes: null,
          created_by: null,
          created_at: h.date,
        })),
        current_value: 99,
        previous_value: 98.5,
        variation: 0.5,
        trend: 'up',
      },
      {
        id: 'kpi-ebitda',
        name: 'EBITDA',
        description: 'Lucros antes de juros, impostos, depreciação e amortização',
        category: 'financeiro' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-1',
        team_id: 'team-financeiro',
        unit: 'R$',
        direction: 'up',
        frequency: 'monthly',
        target_value: 350000,
        status: 'active',
        source_type: 'spreadsheet',
        source_config: { sheetId: 'abc123', cell: 'B15' },
        visibility: 'restricted',
        linked_okrs: [],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-1', display_name: 'Maria Silva', photo_url: null },
        team: { id: 'team-financeiro', name: 'Financeiro' },
        values: generateHistory(280000, 12, 0.05, 'up').map((h, i) => ({
          id: `val-ebitda-${i}`,
          kpi_id: 'kpi-ebitda',
          value: h.value,
          reference_date: h.date,
          source: 'spreadsheet' as const,
          notes: null,
          created_by: null,
          created_at: h.date,
        })),
        current_value: 285000,
        previous_value: 270000,
        variation: 5.5,
        trend: 'up',
      },
      // Growth
      {
        id: 'kpi-leads',
        name: 'Leads Qualificados',
        description: 'Total de leads qualificados no mês',
        category: 'growth' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-3',
        team_id: 'team-marketing',
        unit: 'número',
        direction: 'up',
        frequency: 'weekly',
        target_value: 500,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/crm/leads' },
        visibility: 'bu',
        linked_okrs: ['okr-4'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-3', display_name: 'Ana Rodrigues', photo_url: null },
        team: { id: 'team-marketing', name: 'Marketing' },
        values: generateHistory(420, 8, 0.08, 'up').map((h, i) => ({
          id: `val-leads-${i}`,
          kpi_id: 'kpi-leads',
          value: Math.round(h.value),
          reference_date: h.date,
          source: 'api' as const,
          notes: null,
          created_by: null,
          created_at: h.date,
        })),
        current_value: 456,
        previous_value: 420,
        variation: 8.6,
        trend: 'up',
      },
      {
        id: 'kpi-conversion',
        name: 'Taxa de Conversão',
        description: 'Conversão de trial para cliente',
        category: 'growth' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-3',
        team_id: 'team-vendas',
        unit: '%',
        direction: 'up',
        frequency: 'weekly',
        target_value: 25,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/sales/conversion' },
        visibility: 'bu',
        linked_okrs: ['okr-4', 'okr-5'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-3', display_name: 'Ana Rodrigues', photo_url: null },
        team: { id: 'team-vendas', name: 'Vendas' },
        values: generateHistory(18, 8, 0.05, 'down').map((h, i) => ({
          id: `val-conv-${i}`,
          kpi_id: 'kpi-conversion',
          value: Math.round(h.value * 10) / 10,
          reference_date: h.date,
          source: 'api' as const,
          notes: null,
          created_by: null,
          created_at: h.date,
        })),
        current_value: 16.5,
        previous_value: 18.2,
        variation: -9.3,
        trend: 'down',
        last_update_failed: false,
      },
      // Customer Success
      {
        id: 'kpi-nps',
        name: 'NPS',
        description: 'Net Promoter Score',
        category: 'cs' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-2',
        team_id: 'team-cs',
        unit: 'score',
        direction: 'up',
        frequency: 'monthly',
        target_value: 70,
        status: 'active',
        source_type: 'webhook',
        source_config: { webhookId: 'wh-nps-123' },
        visibility: 'bu',
        linked_okrs: ['okr-3'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-2', display_name: 'João Costa', photo_url: null },
        team: { id: 'team-cs', name: 'Customer Success' },
        values: generateHistory(56, 12, 0.03, 'up').map((h, i) => ({
          id: `val-nps-${i}`,
          kpi_id: 'kpi-nps',
          value: Math.round(h.value),
          reference_date: h.date,
          source: 'webhook' as const,
          notes: null,
          created_by: null,
          created_at: h.date,
        })),
        current_value: 56,
        previous_value: 54,
        variation: 3.7,
        trend: 'up',
      },
      {
        id: 'kpi-churn',
        name: 'Churn Rate',
        description: 'Taxa de cancelamento mensal',
        category: 'cs' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-2',
        team_id: 'team-cs',
        unit: '%',
        direction: 'down',
        frequency: 'monthly',
        target_value: 2,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/metrics/churn' },
        visibility: 'bu',
        linked_okrs: ['okr-3'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-2', display_name: 'João Costa', photo_url: null },
        team: { id: 'team-cs', name: 'Customer Success' },
        values: generateHistory(3.2, 12, 0.1, 'down').map((h, i) => ({
          id: `val-churn-${i}`,
          kpi_id: 'kpi-churn',
          value: Math.round(h.value * 10) / 10,
          reference_date: h.date,
          source: 'api' as const,
          notes: null,
          created_by: null,
          created_at: h.date,
        })),
        current_value: 2.8,
        previous_value: 3.1,
        variation: -9.7,
        trend: 'down',
      },
      // Produto
      {
        id: 'kpi-dau',
        name: 'DAU',
        description: 'Daily Active Users',
        category: 'produto' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-4',
        team_id: 'team-produto',
        unit: 'número',
        direction: 'up',
        frequency: 'daily',
        target_value: 5000,
        status: 'active',
        source_type: 'database',
        source_config: { query: 'SELECT COUNT(*) FROM active_users WHERE date = CURRENT_DATE' },
        visibility: 'team',
        linked_okrs: ['okr-6'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-4', display_name: 'Carlos Lima', photo_url: null },
        team: { id: 'team-produto', name: 'Produto' },
        values: generateHistory(4200, 30, 0.03, 'up').map((h, i) => ({
          id: `val-dau-${i}`,
          kpi_id: 'kpi-dau',
          value: Math.round(h.value),
          reference_date: h.date,
          source: 'database' as const,
          notes: null,
          created_by: null,
          created_at: h.date,
        })),
        current_value: 4350,
        previous_value: 4200,
        variation: 3.6,
        trend: 'up',
      },
      {
        id: 'kpi-feature-adoption',
        name: 'Adoção de Features',
        description: 'Percentual de usuários usando novas features',
        category: 'produto' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-4',
        team_id: 'team-produto',
        unit: '%',
        direction: 'up',
        frequency: 'weekly',
        target_value: 60,
        status: 'active',
        source_type: 'manual',
        source_config: null,
        visibility: 'team',
        linked_okrs: [],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-4', display_name: 'Carlos Lima', photo_url: null },
        team: { id: 'team-produto', name: 'Produto' },
        values: generateHistory(42, 8, 0.04, 'up').map((h, i) => ({
          id: `val-feature-${i}`,
          kpi_id: 'kpi-feature-adoption',
          value: Math.round(h.value),
          reference_date: h.date,
          source: 'manual' as const,
          notes: null,
          created_by: 'user-4',
          created_at: h.date,
        })),
        current_value: 45,
        previous_value: 42,
        variation: 7.1,
        trend: 'up',
      },
      // Operações
      {
        id: 'kpi-uptime',
        name: 'Uptime',
        description: 'Disponibilidade do sistema',
        category: 'operacoes' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-5',
        team_id: 'team-infra',
        unit: '%',
        direction: 'up',
        frequency: 'daily',
        target_value: 99.9,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/monitoring/uptime' },
        visibility: 'bu',
        linked_okrs: [],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-5', display_name: 'Pedro Santos', photo_url: null },
        team: { id: 'team-infra', name: 'Infraestrutura' },
        values: generateHistory(99.85, 30, 0.001, 'stable').map((h, i) => ({
          id: `val-uptime-${i}`,
          kpi_id: 'kpi-uptime',
          value: Math.min(100, Math.round(h.value * 100) / 100),
          reference_date: h.date,
          source: 'api' as const,
          notes: null,
          created_by: null,
          created_at: h.date,
        })),
        current_value: 99.87,
        previous_value: 99.82,
        variation: 0.05,
        trend: 'up',
      },
      {
        id: 'kpi-ticket-resolution',
        name: 'Tempo Médio de Resolução',
        description: 'Tempo médio para resolver tickets de suporte',
        category: 'operacoes' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-6',
        team_id: 'team-suporte',
        unit: 'horas',
        direction: 'down',
        frequency: 'weekly',
        target_value: 4,
        status: 'active',
        source_type: 'api',
        source_config: { endpoint: '/api/support/resolution-time' },
        visibility: 'team',
        linked_okrs: ['okr-7'],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-6', display_name: 'Fernanda Oliveira', photo_url: null },
        team: { id: 'team-suporte', name: 'Suporte' },
        values: generateHistory(6.5, 8, 0.08, 'down').map((h, i) => ({
          id: `val-ticket-${i}`,
          kpi_id: 'kpi-ticket-resolution',
          value: Math.round(h.value * 10) / 10,
          reference_date: h.date,
          source: 'api' as const,
          notes: null,
          created_by: null,
          created_at: h.date,
        })),
        current_value: 5.8,
        previous_value: 6.2,
        variation: -6.5,
        trend: 'down',
      },
      // Pessoas
      {
        id: 'kpi-enps',
        name: 'eNPS',
        description: 'Employee Net Promoter Score',
        category: 'pessoas' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-7',
        team_id: 'team-rh',
        unit: 'score',
        direction: 'up',
        frequency: 'quarterly',
        target_value: 50,
        status: 'active',
        source_type: 'manual',
        source_config: null,
        visibility: 'restricted',
        linked_okrs: [],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-7', display_name: 'Lucia Mendes', photo_url: null },
        team: { id: 'team-rh', name: 'RH' },
        values: [
          { id: 'val-enps-1', kpi_id: 'kpi-enps', value: 42, reference_date: '2024-03-31', source: 'manual' as const, notes: 'Q1 2024', created_by: 'user-7', created_at: '2024-04-01' },
          { id: 'val-enps-2', kpi_id: 'kpi-enps', value: 45, reference_date: '2024-06-30', source: 'manual' as const, notes: 'Q2 2024', created_by: 'user-7', created_at: '2024-07-01' },
          { id: 'val-enps-3', kpi_id: 'kpi-enps', value: 48, reference_date: '2024-09-30', source: 'manual' as const, notes: 'Q3 2024', created_by: 'user-7', created_at: '2024-10-01' },
        ],
        current_value: 48,
        previous_value: 45,
        variation: 6.7,
        trend: 'up',
      },
      {
        id: 'kpi-turnover',
        name: 'Turnover Voluntário',
        description: 'Taxa de saída voluntária de colaboradores',
        category: 'pessoas' as KpiCategory,
        bu_id: buId,
        owner_user_id: 'user-7',
        team_id: 'team-rh',
        unit: '%',
        direction: 'down',
        frequency: 'monthly',
        target_value: 5,
        status: 'active',
        source_type: 'manual',
        source_config: null,
        visibility: 'restricted',
        linked_okrs: [],
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-12-01T00:00:00Z',
        deleted_at: null,
        owner: { id: 'user-7', display_name: 'Lucia Mendes', photo_url: null },
        team: { id: 'team-rh', name: 'RH' },
        values: generateHistory(8, 12, 0.1, 'down').map((h, i) => ({
          id: `val-turnover-${i}`,
          kpi_id: 'kpi-turnover',
          value: Math.round(h.value * 10) / 10,
          reference_date: h.date,
          source: 'manual' as const,
          notes: null,
          created_by: 'user-7',
          created_at: h.date,
        })),
        current_value: 7.2,
        previous_value: 7.8,
        variation: -7.7,
        trend: 'down',
      },
    ];

    // Calculate RAG status for each KPI
    return kpisData.map(kpi => ({
      ...kpi,
      rag_status: calculateRagStatus(kpi.current_value, kpi.target_value, kpi.direction),
    }));
  }, []);

  // Summary stats
  const summary = useMemo(() => {
    const total = mockKpis.length;
    const onTrack = mockKpis.filter(k => k.rag_status === 'on_track').length;
    const atRisk = mockKpis.filter(k => k.rag_status === 'at_risk').length;
    const offTrack = mockKpis.filter(k => k.rag_status === 'off_track').length;
    const noData = mockKpis.filter(k => k.rag_status === 'no_data').length;
    const improving = mockKpis.filter(k => 
      (k.direction === 'up' && k.trend === 'up') ||
      (k.direction === 'down' && k.trend === 'down')
    ).length;

    return { total, onTrack, atRisk, offTrack, noData, improving };
  }, [mockKpis]);

  return {
    kpis: mockKpis,
    summary,
    isLoading: false,
  };
}
