// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/lib/context.ts
import { ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { ToolError } from "npm:@lovable.dev/mcp-js@2.0.4";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (ou VITE_SUPABASE_URL) \xE9 obrigat\xF3rio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS ou SUPABASE_ANON_KEY \xE9 obrigat\xF3rio"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) {
    throw new ToolError("Sess\xE3o n\xE3o identificada. Reconecte o Next no seu assistente.");
  }
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/lib/result.ts
import { ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@2.0.4";
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
function assertNoError(error, what) {
  if (!error) return;
  if (error.code === "42501" || error.code === "PGRST301") {
    throw new ToolError2(`Sem permiss\xE3o para consultar ${what} nesta unidade.`);
  }
  throw new ToolError2(`Erro ao consultar ${what}: ${error.message}`);
}
function clampLimit(limit, fallback = 50, max = 200) {
  const value = Number(limit ?? fallback);
  if (!Number.isFinite(value) || value <= 0) return fallback;
  return Math.min(Math.trunc(value), max);
}

// src/lib/mcp/lib/context.ts
function firstUnit(value) {
  if (!value) return null;
  return Array.isArray(value) ? value[0] ?? null : value;
}
async function resolveIdentity(ctx) {
  if (!ctx.isAuthenticated()) {
    throw new ToolError3("N\xE3o autenticado. Conecte o Next no seu assistente e entre com sua conta.");
  }
  const supabase = supabaseForUser(ctx);
  const userId = ctx.getUserId();
  const { data: profile, error: profileError } = await supabase.from("profiles").select("id, display_name, user_type, work_email, email").eq("user_id", userId).is("deleted_at", null).maybeSingle();
  assertNoError(profileError, "seu perfil");
  if (!profile) {
    throw new ToolError3("N\xE3o encontrei seu perfil no Next. Verifique se sua conta est\xE1 ativa.");
  }
  const { data: memberships, error: membershipError } = await supabase.from("bu_user_memberships").select("bu_id, role_in_bu, is_default, bu_units!inner(id, name, slug, status)").eq("profile_id", profile.id).is("deleted_at", null);
  assertNoError(membershipError, "suas unidades");
  const bus = (memberships ?? []).map((m) => {
    const row = m;
    return { unit: firstUnit(row.bu_units), role: row.role_in_bu, isDefault: !!row.is_default };
  }).filter((row) => row.unit?.status === "active").map((row) => ({
    id: row.unit.id,
    name: row.unit.name,
    slug: row.unit.slug,
    role_in_bu: row.role,
    is_default: row.isDefault
  }));
  if (bus.length === 0) {
    const { data: assoc } = await supabase.from("partner_contact_bu_associations").select("bu_id, is_active, bu_units!inner(id, name, slug, status)").eq("is_active", true);
    for (const row of assoc ?? []) {
      const unit = firstUnit(row.bu_units);
      if (unit?.status === "active" && !bus.some((b) => b.id === unit.id)) {
        bus.push({ id: unit.id, name: unit.name, slug: unit.slug, role_in_bu: "external", is_default: false });
      }
    }
  }
  return {
    supabase,
    profileId: profile.id,
    displayName: profile.display_name ?? null,
    userType: profile.user_type ?? null,
    email: profile.work_email ?? profile.email ?? null,
    bus
  };
}
async function resolveScope(ctx, bu) {
  const identity = await resolveIdentity(ctx);
  if (identity.bus.length === 0) {
    throw new ToolError3("Sua conta n\xE3o est\xE1 vinculada a nenhuma unidade ativa no Next.");
  }
  let chosen;
  const needle = bu?.trim().toLowerCase();
  if (needle) {
    chosen = identity.bus.find(
      (b) => b.id.toLowerCase() === needle || (b.slug ?? "").toLowerCase() === needle || b.name.toLowerCase() === needle || b.name.toLowerCase().includes(needle)
    );
    if (!chosen) {
      throw new ToolError3(
        `N\xE3o encontrei a unidade "${bu}" entre as suas: ${identity.bus.map((b) => b.name).join(", ")}.`
      );
    }
  } else if (identity.bus.length === 1) {
    chosen = identity.bus[0];
  } else {
    chosen = identity.bus.find((b) => b.is_default);
    if (!chosen) {
      throw new ToolError3(
        `Voc\xEA tem acesso a v\xE1rias unidades. Informe qual usar: ${identity.bus.map((b) => b.name).join(", ")}.`
      );
    }
  }
  return { ...identity, buId: chosen.id, buName: chosen.name };
}
async function resolvePerson(scope, person) {
  const needle = person.trim();
  const { data, error } = await scope.supabase.from("profiles").select("id, display_name, first_name, last_name, work_email, email, team_id").eq("bu_id", scope.buId).is("deleted_at", null).or(
    [
      `id.eq.${/^[0-9a-f-]{36}$/i.test(needle) ? needle : "00000000-0000-0000-0000-000000000000"}`,
      `work_email.ilike.%${needle}%`,
      `email.ilike.%${needle}%`,
      `display_name.ilike.%${needle}%`,
      `first_name.ilike.%${needle}%`,
      `last_name.ilike.%${needle}%`
    ].join(",")
  ).limit(10);
  assertNoError(error, "pessoas");
  const rows = data ?? [];
  if (rows.length === 0) throw new ToolError3(`N\xE3o encontrei "${person}" na unidade ${scope.buName}.`);
  if (rows.length > 1) {
    const exact = rows.find(
      (r) => r.work_email?.toLowerCase() === needle.toLowerCase() || r.email?.toLowerCase() === needle.toLowerCase() || r.display_name?.toLowerCase() === needle.toLowerCase()
    );
    if (!exact) {
      throw new ToolError3(
        `Encontrei mais de uma pessoa para "${person}": ${rows.map((r) => `${r.display_name} <${r.work_email ?? r.email ?? "sem e-mail"}>`).join("; ")}. Refine a busca.`
      );
    }
    return {
      id: exact.id,
      display_name: exact.display_name ?? null,
      team_id: exact.team_id ?? null
    };
  }
  const only = rows[0];
  return {
    id: only.id,
    display_name: only.display_name ?? null,
    team_id: only.team_id ?? null
  };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu no Next",
  description: "Retorna o perfil do usu\xE1rio conectado e as unidades de neg\xF3cio a que ele tem acesso. Use antes das outras ferramentas quando n\xE3o souber qual unidade usar.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const identity = await resolveIdentity(ctx);
    return jsonResult({
      perfil: {
        id: identity.profileId,
        nome: identity.displayName,
        email: identity.email,
        tipo: identity.userType
      },
      unidades: identity.bus.map((b) => ({
        id: b.id,
        nome: b.name,
        slug: b.slug,
        papel: b.role_in_bu,
        padrao: b.is_default
      }))
    });
  }
});

// src/lib/mcp/tools/list-people.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";

// src/lib/mcp/lib/args.ts
import { z } from "npm:zod@^3.25.76";
var buArg = z.string().optional().describe("Unidade de neg\xF3cio (nome, slug ou id). Omita para usar a sua unidade padr\xE3o.");
var limitArg = z.number().int().positive().optional().describe("Quantidade m\xE1xima de registros (padr\xE3o 50, m\xE1ximo 200).");
var searchArg = z.string().optional().describe("Texto para filtrar por nome/t\xEDtulo.");

// src/lib/mcp/tools/list-people.ts
var list_people_default = defineTool2({
  name: "list_people",
  title: "Listar pessoas",
  description: "Lista as pessoas (jetimobers) da unidade com time, cargo, modelo de trabalho e situa\xE7\xE3o. Aceita busca por nome ou e-mail. N\xE3o retorna dados pessoais sens\xEDveis.",
  inputSchema: {
    bu: buArg,
    busca: searchArg,
    situacao: z2.enum(["active", "vacation", "terminated", "external"]).optional().describe("Filtra pela situa\xE7\xE3o (padr\xE3o: apenas ativos)."),
    modelo_trabalho: z2.enum(["onsite", "hybrid", "remote"]).optional(),
    time: z2.string().optional().describe("Nome do time para filtrar."),
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, busca, situacao, modelo_trabalho, time, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    let teamId = null;
    if (time) {
      const { data: teams, error: error2 } = await scope.supabase.from("teams").select("id, name").eq("bu_id", scope.buId).is("deleted_at", null).ilike("name", `%${time}%`).limit(1);
      assertNoError(error2, "times");
      teamId = teams?.[0]?.id ?? null;
      if (!teamId) return jsonResult({ unidade: scope.buName, aviso: `Time "${time}" n\xE3o encontrado.`, pessoas: [] });
    }
    let query = scope.supabase.from("profiles").select(
      "id, display_name, work_email, email, employment_status, work_mode, city, state, start_date, team_id, job_title_id, manager_user_id, user_type, teams(name), job_titles(name)"
    ).eq("bu_id", scope.buId).is("deleted_at", null).order("display_name").limit(clampLimit(limite, 100));
    query = query.eq("employment_status", situacao ?? "active");
    if (modelo_trabalho) query = query.eq("work_mode", modelo_trabalho);
    if (teamId) query = query.eq("team_id", teamId);
    if (busca) {
      query = query.or(
        [
          `display_name.ilike.%${busca}%`,
          `first_name.ilike.%${busca}%`,
          `last_name.ilike.%${busca}%`,
          `work_email.ilike.%${busca}%`,
          `email.ilike.%${busca}%`
        ].join(",")
      );
    }
    const { data, error } = await query;
    assertNoError(error, "pessoas");
    const pessoas = (data ?? []).map((p) => ({
      id: p.id,
      nome: p.display_name,
      email: p.work_email ?? p.email,
      situacao: p.employment_status,
      modelo_trabalho: p.work_mode,
      cidade: p.city,
      estado: p.state,
      inicio: p.start_date,
      tipo: p.user_type,
      time: (Array.isArray(p.teams) ? p.teams[0] : p.teams)?.name ?? null,
      cargo: (Array.isArray(p.job_titles) ? p.job_titles[0] : p.job_titles)?.name ?? null,
      gestor_id: p.manager_user_id
    }));
    return jsonResult({ unidade: scope.buName, total: pessoas.length, pessoas });
  }
});

// src/lib/mcp/tools/person-performance.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";

// src/modules/okrs/utils/progressCalculation.ts
var UNIT_MULTIPLIERS = {
  "R$": 1,
  "R$ mil": 1e3,
  "R$ milh\xE3o": 1e6
};
function normalizeValueByUnit(value, unit) {
  const multiplier = unit ? UNIT_MULTIPLIERS[unit] : void 0;
  return multiplier ? value * multiplier : value;
}
function calculateDirectionalProgress(baseline, current, target, direction) {
  if (direction === "maintain") {
    return current >= target ? 100 : 0;
  }
  if (direction === "up") {
    if (target === baseline) {
      return current >= target ? 100 : 0;
    }
    const progress2 = (current - baseline) / (target - baseline) * 100;
    return Math.max(0, progress2);
  }
  if (baseline <= target) {
    if (current <= target) return 100;
    if (baseline === target) return 0;
    return Math.max(0, target / current * 100);
  }
  const progress = (baseline - current) / (baseline - target) * 100;
  return Math.max(0, progress);
}
function normalizeProgressInputs(baseline, current, target, context) {
  const direct = { baseline, current, target };
  if (!context?.unit || !(context.unit in UNIT_MULTIPLIERS)) {
    return direct;
  }
  const multiplier = UNIT_MULTIPLIERS[context.unit];
  const scaledTarget = {
    baseline: normalizeValueByUnit(baseline, context.unit),
    current,
    target: normalizeValueByUnit(target, context.unit)
  };
  const directProgress = calculateDirectionalProgress(
    direct.baseline,
    direct.current,
    direct.target,
    "up"
  );
  const scaledProgress = calculateDirectionalProgress(
    scaledTarget.baseline,
    scaledTarget.current,
    scaledTarget.target,
    "up"
  );
  if (directProgress > 1e3 && scaledProgress >= 0 && scaledProgress <= 1e3) {
    return scaledTarget;
  }
  return {
    baseline,
    current,
    target
  };
}
function calculateProgress(baseline, current, target, direction, context) {
  const normalized = normalizeProgressInputs(baseline, current, target, context);
  return calculateDirectionalProgress(normalized.baseline, normalized.current, normalized.target, direction);
}

// src/lib/mcp/lib/person-performance.ts
var DAY = 24 * 60 * 60 * 1e3;
async function buildPersonPerformance(scope, profileId) {
  const { supabase, buId } = scope;
  const [
    profileRes,
    objectivesRes,
    krsRes,
    orgKrsRes,
    checkinsRes,
    kpisRes,
    kpiContribRes,
    projectsRes,
    milestonesRes,
    initiativesRes
  ] = await Promise.all([
    supabase.from("profiles").select(
      "id, display_name, work_email, email, employment_status, work_mode, city, state, start_date, team_id, job_title_id, manager_user_id, user_type"
    ).eq("id", profileId).maybeSingle(),
    supabase.from("okr_team_objectives").select("id, title, status, health_status, avg_progress, kr_count, team_id, cycle_id, is_shared").eq("bu_id", buId).eq("owner_user_id", profileId).is("deleted_at", null).is("cancelled_at", null),
    supabase.from("okr_team_key_results").select(
      "id, title, type, baseline, current_value, target, direction, unit, status, team_id, team_objective_id, last_checkin_at, okr_team_objectives(title, cycle_id)"
    ).eq("bu_id", buId).eq("owner_user_id", profileId).is("deleted_at", null).is("cancelled_at", null),
    supabase.from("okr_org_key_results").select(
      "id, title, baseline, current_value, target, direction, unit, status, org_objective_id, okr_org_objectives(title, cycle_id)"
    ).eq("bu_id", buId).eq("owner_user_id", profileId).is("deleted_at", null).is("cancelled_at", null),
    supabase.from("okr_checkins").select("id, kr_id, date, previous_value, current_value, confidence, blockers, comments").eq("bu_id", buId).eq("user_id", profileId).order("date", { ascending: false }).limit(15),
    supabase.from("kpi_metrics").select(
      "id, name, category, unit, direction, target_value, status, lifecycle_status, consolidation_frequency, update_frequency, team_id, area_id, scope"
    ).eq("bu_id", buId).eq("owner_user_id", profileId).is("deleted_at", null),
    supabase.from("kpi_data_contributors").select("kpi_id, role, kpi_metrics!inner(id, name, unit, direction, target_value, status, bu_id)").eq("profile_id", profileId),
    supabase.from("projects").select("id, name, status, start_date, due_date").eq("bu_id", buId).eq("owner_id", profileId).is("deleted_at", null),
    supabase.from("project_milestones").select("id, name, status, due_date, project_id, projects(name)").eq("bu_id", buId).eq("owner_id", profileId).is("deleted_at", null),
    supabase.from("okr_initiatives").select("id, name, status, priority, progress, expected_end_date, kr_id").eq("bu_id", buId).eq("owner_user_id", profileId).is("deleted_at", null)
  ]);
  assertNoError(profileRes.error, "o perfil da pessoa");
  assertNoError(objectivesRes.error, "objetivos");
  assertNoError(krsRes.error, "key results");
  assertNoError(projectsRes.error, "projetos");
  const alertas = [];
  const now = Date.now();
  const krs = (krsRes.data ?? []).map((kr) => {
    const progresso = calculateProgress(
      Number(kr.baseline) || 0,
      Number(kr.current_value) || 0,
      Number(kr.target) || 0,
      kr.direction ?? "up",
      { unit: kr.unit }
    );
    const objetivo = Array.isArray(kr.okr_team_objectives) ? kr.okr_team_objectives[0] : kr.okr_team_objectives;
    const semCheckin = !kr.last_checkin_at || now - new Date(kr.last_checkin_at).getTime() > 14 * DAY;
    if (kr.status === "active" && semCheckin) {
      alertas.push(`KR sem check-in recente: ${kr.title}`);
    }
    if (kr.status === "active" && progresso < 40) {
      alertas.push(`KR abaixo de 40%: ${kr.title} (${Math.round(progresso)}%)`);
    }
    return {
      id: kr.id,
      titulo: kr.title,
      tipo: kr.type,
      objetivo: objetivo?.title ?? null,
      baseline: kr.baseline,
      resultado: kr.current_value,
      meta: kr.target,
      orientacao: kr.direction,
      unidade: kr.unit,
      status: kr.status,
      progresso_pct: Math.round(progresso),
      ultimo_checkin: kr.last_checkin_at
    };
  });
  const orgKrs = (orgKrsRes.data ?? []).map((kr) => ({
    id: kr.id,
    titulo: kr.title,
    escopo: "org",
    objetivo: (Array.isArray(kr.okr_org_objectives) ? kr.okr_org_objectives[0] : kr.okr_org_objectives)?.title ?? null,
    resultado: kr.current_value,
    meta: kr.target,
    orientacao: kr.direction,
    unidade: kr.unit,
    status: kr.status,
    progresso_pct: Math.round(
      calculateProgress(
        Number(kr.baseline) || 0,
        Number(kr.current_value) || 0,
        Number(kr.target) || 0,
        kr.direction ?? "up",
        { unit: kr.unit }
      )
    )
  }));
  const kpiIds = [
    ...(kpisRes.data ?? []).map((k) => k.id),
    ...(kpiContribRes.data ?? []).filter((c) => {
      const m = Array.isArray(c.kpi_metrics) ? c.kpi_metrics[0] : c.kpi_metrics;
      return m?.bu_id === buId;
    }).map((c) => c.kpi_id)
  ].filter((id, i, arr) => arr.indexOf(id) === i);
  let ultimosValores = {};
  if (kpiIds.length > 0) {
    const { data: values, error: valuesError } = await supabase.from("kpi_values").select("kpi_id, value, reference_date, input_type").in("kpi_id", kpiIds).order("reference_date", { ascending: false }).limit(500);
    assertNoError(valuesError, "valores de KPI");
    for (const v of values ?? []) {
      const key = v.kpi_id;
      if (!ultimosValores[key]) {
        ultimosValores[key] = {
          value: Number(v.value),
          reference_date: v.reference_date,
          input_type: v.input_type ?? null
        };
      }
    }
  }
  const kpis = [
    ...(kpisRes.data ?? []).map((k) => ({ ...k, papel: "respons\xE1vel" })),
    ...(kpiContribRes.data ?? []).map((c) => {
      const m = Array.isArray(c.kpi_metrics) ? c.kpi_metrics[0] : c.kpi_metrics;
      return m && m.bu_id === buId ? { ...m, papel: `contribuidor (${c.role})` } : null;
    }).filter((k) => !!k)
  ].map((k) => {
    const ultimo = ultimosValores[k.id];
    const meta = Number(k.target_value);
    if (ultimo && Number.isFinite(meta) && meta !== 0) {
      const fora = k.direction === "down" ? ultimo.value > meta : ultimo.value < meta;
      if (fora) alertas.push(`KPI fora da meta: ${k.name} (${ultimo.value} vs meta ${meta})`);
    }
    if (!ultimo) alertas.push(`KPI sem nenhum valor lan\xE7ado: ${k.name}`);
    return {
      id: k.id,
      nome: k.name,
      papel: k.papel,
      unidade: k.unit,
      orientacao: k.direction,
      meta: k.target_value,
      status: k.status,
      periodicidade_consolidacao: k.consolidation_frequency,
      ultimo_valor: ultimo?.value ?? null,
      ultimo_valor_data: ultimo?.reference_date ?? null,
      ultimo_valor_tipo: ultimo?.input_type ?? null
    };
  });
  const marcos = (milestonesRes.data ?? []).map((m) => {
    const atrasado = m.status !== "done" && m.due_date && new Date(m.due_date).getTime() < now;
    if (atrasado) alertas.push(`Marco atrasado: ${m.name}`);
    return {
      id: m.id,
      nome: m.name,
      status: m.status,
      prazo: m.due_date,
      atrasado: !!atrasado,
      projeto: (Array.isArray(m.projects) ? m.projects[0] : m.projects)?.name ?? null
    };
  });
  const profile = profileRes.data ?? {};
  return {
    pessoa: {
      id: profile.id,
      nome: profile.display_name,
      email: profile.work_email ?? profile.email,
      situacao: profile.employment_status,
      modelo_trabalho: profile.work_mode,
      cidade: profile.city,
      estado: profile.state,
      inicio: profile.start_date,
      tipo: profile.user_type,
      time_id: profile.team_id,
      cargo_id: profile.job_title_id,
      gestor_id: profile.manager_user_id,
      unidade: scope.buName
    },
    okrs: {
      objetivos: (objectivesRes.data ?? []).map((o) => ({
        id: o.id,
        titulo: o.title,
        status: o.status,
        saude: o.health_status,
        progresso_medio: o.avg_progress,
        qtd_krs: o.kr_count,
        compartilhado: o.is_shared
      })),
      key_results: [...krs, ...orgKrs]
    },
    checkins_recentes: (checkinsRes.data ?? []).map((c) => ({
      kr_id: c.kr_id,
      data: c.date,
      de: c.previous_value,
      para: c.current_value,
      confianca: c.confidence,
      bloqueios: c.blockers,
      comentarios: c.comments
    })),
    kpis,
    projetos: {
      projetos: (projectsRes.data ?? []).map((p) => ({
        id: p.id,
        nome: p.name,
        status: p.status,
        inicio: p.start_date,
        prazo: p.due_date
      })),
      marcos
    },
    alertas: [
      ...alertas,
      ...(initiativesRes.data ?? []).filter((i) => i.status === "blocked").map((i) => `Iniciativa bloqueada: ${i.name}`)
    ].filter((a, i, arr) => arr.indexOf(a) === i)
  };
}

// src/lib/mcp/tools/person-performance.ts
var person_performance_default = defineTool3({
  name: "person_performance",
  title: "Performance de uma pessoa",
  description: "Panorama consolidado de performance de um jetimober: dados de trabalho, objetivos e KRs sob responsabilidade com progresso, check-ins recentes, KPIs com \xFAltimo valor e meta, projetos e marcos, e alertas do que merece aten\xE7\xE3o.",
  inputSchema: {
    pessoa: z3.string().describe("Nome, e-mail ou id da pessoa."),
    bu: buArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ pessoa, bu }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    const person = await resolvePerson(scope, pessoa);
    const performance = await buildPersonPerformance(scope, person.id);
    return jsonResult({ unidade: scope.buName, ...performance });
  }
});

// src/lib/mcp/tools/team-performance.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var team_performance_default = defineTool4({
  name: "team_performance",
  title: "Performance de um time",
  description: "Panorama de performance de todas as pessoas ativas de um time: objetivos, KRs com progresso, KPIs e alertas por pessoa. Use para comparar o time.",
  inputSchema: {
    time: z4.string().describe("Nome do time."),
    bu: buArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ time, bu }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    const { data: teams, error: teamError } = await scope.supabase.from("teams").select("id, name").eq("bu_id", scope.buId).is("deleted_at", null).ilike("name", `%${time}%`).limit(1);
    assertNoError(teamError, "times");
    const team = teams?.[0];
    if (!team) return jsonResult({ aviso: `Time "${time}" n\xE3o encontrado na unidade ${scope.buName}.` });
    const { data: people, error: peopleError } = await scope.supabase.from("profiles").select("id, display_name").eq("bu_id", scope.buId).eq("team_id", team.id).eq("employment_status", "active").is("deleted_at", null).order("display_name").limit(40);
    assertNoError(peopleError, "pessoas do time");
    const results = await Promise.all(
      (people ?? []).map(async (p) => {
        const performance = await buildPersonPerformance(scope, p.id);
        return {
          pessoa: p.display_name,
          objetivos: performance.okrs.objetivos.length,
          key_results: performance.okrs.key_results,
          kpis: performance.kpis,
          projetos: performance.projetos.projetos.length,
          alertas: performance.alertas
        };
      })
    );
    return jsonResult({ unidade: scope.buName, time: team.name, pessoas: results });
  }
});

// src/lib/mcp/tools/list-org-structure.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.0.4";
var list_org_structure_default = defineTool5({
  name: "list_org_structure",
  title: "Estrutura da unidade",
  description: "Lista times, \xE1reas, squads e cargos da unidade, com l\xEDderes e situa\xE7\xE3o. Use para entender a estrutura antes de consultar pessoas ou OKRs.",
  inputSchema: { bu: buArg },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    const { supabase, buId } = scope;
    const [teams, areas, squads, jobTitles] = await Promise.all([
      supabase.from("teams").select("id, name, description, status, area_id, leader_user_id, parent_team_id").eq("bu_id", buId).is("deleted_at", null).order("name"),
      supabase.from("areas").select("id, name, description, status, leader_user_id, co_leader_user_id").eq("bu_id", buId).is("deleted_at", null).order("name"),
      supabase.from("squads").select("id, name, description, products, status").eq("bu_id", buId).is("deleted_at", null).order("name"),
      supabase.from("job_titles").select("id, name, description, is_active").is("deleted_at", null).order("name")
    ]);
    assertNoError(teams.error, "times");
    assertNoError(areas.error, "\xE1reas");
    return jsonResult({
      unidade: scope.buName,
      times: teams.data ?? [],
      areas: areas.data ?? [],
      squads: squads.data ?? [],
      cargos: (jobTitles.data ?? []).filter((j) => j.is_active)
    });
  }
});

// src/lib/mcp/tools/list-cycles.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z5 } from "npm:zod@^3.25.76";
var list_cycles_default = defineTool6({
  name: "list_cycles",
  title: "Listar ciclos",
  description: "Lista os ciclos de OKR da unidade (ano, trimestre, m\xEAs) com datas, tipo e situa\xE7\xE3o. Use para descobrir o ciclo ativo antes de consultar OKRs.",
  inputSchema: {
    bu: buArg,
    status: z5.enum(["planning", "active", "closed"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, status }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    let query = scope.supabase.from("cycles").select("id, name, type, status, start_date, end_date, parent_cycle_id, review_date, retro_date").eq("bu_id", scope.buId).order("start_date", { ascending: false }).limit(60);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    assertNoError(error, "ciclos");
    return jsonResult({ unidade: scope.buName, ciclos: data ?? [] });
  }
});

// src/lib/mcp/tools/list-objectives.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z6 } from "npm:zod@^3.25.76";
var list_objectives_default = defineTool7({
  name: "list_objectives",
  title: "Listar objetivos (OKRs)",
  description: "Lista objetivos organizacionais e/ou de time da unidade, com ciclo, respons\xE1vel, sa\xFAde, progresso m\xE9dio e quantidade de KRs.",
  inputSchema: {
    bu: buArg,
    escopo: z6.enum(["org", "team", "todos"]).optional().describe("Padr\xE3o: todos."),
    ciclo: z6.string().optional().describe("Nome do ciclo (ex.: 2026-Q3). Omita para o ciclo ativo."),
    time: z6.string().optional().describe("Nome do time."),
    status: z6.enum(["draft", "active", "completed", "cancelled", "discarded"]).optional(),
    busca: searchArg,
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, escopo, ciclo, time, status, busca, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    const { supabase, buId } = scope;
    const limit = clampLimit(limite, 100);
    let cycleId = null;
    let cycleName = null;
    const { data: cycles, error: cyclesError } = await supabase.from("cycles").select("id, name, status").eq("bu_id", buId).order("start_date", { ascending: false }).limit(60);
    assertNoError(cyclesError, "ciclos");
    const chosenCycle = ciclo ? (cycles ?? []).find((c) => c.name.toLowerCase().includes(ciclo.toLowerCase())) : (cycles ?? []).find((c) => c.status === "active");
    if (chosenCycle) {
      cycleId = chosenCycle.id;
      cycleName = chosenCycle.name;
    }
    let teamId = null;
    if (time) {
      const { data: teams } = await supabase.from("teams").select("id, name").eq("bu_id", buId).is("deleted_at", null).ilike("name", `%${time}%`).limit(1);
      teamId = teams?.[0]?.id ?? null;
      if (!teamId) return jsonResult({ aviso: `Time "${time}" n\xE3o encontrado.`, objetivos: [] });
    }
    const wantOrg = !escopo || escopo === "todos" || escopo === "org";
    const wantTeam = !escopo || escopo === "todos" || escopo === "team";
    const orgPromise = wantOrg ? (() => {
      let q = supabase.from("okr_org_objectives").select(
        "id, title, description, status, owner_user_id, cycle_id, year, health_status, health_score, start_date, end_date"
      ).eq("bu_id", buId).is("deleted_at", null).is("cancelled_at", null).limit(limit);
      if (cycleId) q = q.eq("cycle_id", cycleId);
      if (status) q = q.eq("status", status);
      if (busca) q = q.ilike("title", `%${busca}%`);
      return q;
    })() : Promise.resolve({ data: [], error: null });
    const teamPromise = wantTeam ? (() => {
      let q = supabase.from("okr_team_objectives").select(
        "id, title, description, status, owner_user_id, team_id, cycle_id, is_shared, responsibility_model, health_status, health_score, avg_progress, kr_count, teams(name)"
      ).eq("bu_id", buId).is("deleted_at", null).is("cancelled_at", null).limit(limit);
      if (cycleId) q = q.eq("cycle_id", cycleId);
      if (teamId) q = q.eq("team_id", teamId);
      if (status) q = q.eq("status", status);
      if (busca) q = q.ilike("title", `%${busca}%`);
      return q;
    })() : Promise.resolve({ data: [], error: null });
    const [org, team] = await Promise.all([orgPromise, teamPromise]);
    assertNoError(org.error, "objetivos organizacionais");
    assertNoError(team.error, "objetivos de time");
    return jsonResult({
      unidade: scope.buName,
      ciclo: cycleName,
      objetivos_org: org.data ?? [],
      objetivos_time: (team.data ?? []).map((o) => ({
        ...o,
        time: (Array.isArray(o.teams) ? o.teams[0] : o.teams)?.name ?? null,
        teams: void 0
      }))
    });
  }
});

// src/lib/mcp/tools/list-key-results.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z7 } from "npm:zod@^3.25.76";
function progressOf(kr) {
  return calculateProgress(
    Number(kr.baseline) || 0,
    Number(kr.current_value) || 0,
    Number(kr.target) || 0,
    kr.direction ?? "up",
    { unit: kr.unit ?? null }
  );
}
var list_key_results_default = defineTool8({
  name: "list_key_results",
  title: "Listar key results (KRs)",
  description: "Lista KRs de time e organizacionais com baseline, resultado, meta, orienta\xE7\xE3o, progresso calculado, farol e data do \xFAltimo check-in. Permite filtrar por objetivo, time, respons\xE1vel, ciclo e KRs em risco.",
  inputSchema: {
    bu: buArg,
    escopo: z7.enum(["org", "team", "todos"]).optional(),
    objetivo_id: z7.string().optional().describe("Id do objetivo."),
    time: z7.string().optional(),
    ciclo: z7.string().optional().describe("Nome do ciclo. Omita para o ciclo ativo."),
    em_risco: z7.boolean().optional().describe("Se verdadeiro, retorna apenas KRs ativos com progresso abaixo de 70%."),
    busca: searchArg,
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, escopo, objetivo_id, time, ciclo, em_risco, busca, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    const { supabase, buId } = scope;
    const limit = clampLimit(limite, 100);
    const { data: cycles } = await supabase.from("cycles").select("id, name, status").eq("bu_id", buId).order("start_date", { ascending: false }).limit(60);
    const chosenCycle = ciclo ? (cycles ?? []).find((c) => c.name.toLowerCase().includes(ciclo.toLowerCase())) : (cycles ?? []).find((c) => c.status === "active");
    const cycleId = chosenCycle?.id ?? null;
    let teamId = null;
    if (time) {
      const { data: teams } = await supabase.from("teams").select("id, name").eq("bu_id", buId).is("deleted_at", null).ilike("name", `%${time}%`).limit(1);
      teamId = teams?.[0]?.id ?? null;
      if (!teamId) return jsonResult({ aviso: `Time "${time}" n\xE3o encontrado.`, key_results: [] });
    }
    const wantTeam = !escopo || escopo === "todos" || escopo === "team";
    const wantOrg = !escopo || escopo === "todos" || escopo === "org";
    const teamPromise = wantTeam ? (() => {
      let q = supabase.from("okr_team_key_results").select(
        "id, title, type, baseline, current_value, target, direction, unit, status, team_id, team_objective_id, owner_user_id, last_checkin_at, linked_org_kr_id, okr_team_objectives!inner(id, title, cycle_id, team_id), teams(name)"
      ).eq("bu_id", buId).is("deleted_at", null).is("cancelled_at", null).limit(limit);
      if (objetivo_id) q = q.eq("team_objective_id", objetivo_id);
      if (teamId) q = q.eq("team_id", teamId);
      if (cycleId && !objetivo_id) q = q.eq("okr_team_objectives.cycle_id", cycleId);
      if (busca) q = q.ilike("title", `%${busca}%`);
      return q;
    })() : Promise.resolve({ data: [], error: null });
    const orgPromise = wantOrg ? (() => {
      let q = supabase.from("okr_org_key_results").select(
        "id, title, baseline, current_value, target, direction, unit, status, org_objective_id, owner_user_id, okr_org_objectives!inner(id, title, cycle_id)"
      ).eq("bu_id", buId).is("deleted_at", null).is("cancelled_at", null).limit(limit);
      if (objetivo_id) q = q.eq("org_objective_id", objetivo_id);
      if (cycleId && !objetivo_id) q = q.eq("okr_org_objectives.cycle_id", cycleId);
      if (busca) q = q.ilike("title", `%${busca}%`);
      return q;
    })() : Promise.resolve({ data: [], error: null });
    const [teamRes, orgRes] = await Promise.all([teamPromise, orgPromise]);
    assertNoError(teamRes.error, "KRs de time");
    assertNoError(orgRes.error, "KRs organizacionais");
    const map = (row, escopoLabel) => {
      const parent = escopoLabel === "team" ? row.okr_team_objectives : row.okr_org_objectives;
      const objetivo = Array.isArray(parent) ? parent[0] : parent;
      return {
        id: row.id,
        escopo: escopoLabel,
        titulo: row.title,
        tipo: row.type ?? null,
        objetivo: objetivo?.title ?? null,
        objetivo_id: objetivo?.id ?? null,
        time: (Array.isArray(row.teams) ? row.teams[0] : row.teams)?.name ?? null,
        responsavel_id: row.owner_user_id,
        baseline: row.baseline,
        resultado: row.current_value,
        meta: row.target,
        orientacao: row.direction,
        unidade: row.unit,
        status: row.status,
        progresso_pct: Math.round(progressOf(row)),
        ultimo_checkin: row.last_checkin_at ?? null
      };
    };
    let krs = [
      ...(teamRes.data ?? []).map((r) => map(r, "team")),
      ...(orgRes.data ?? []).map((r) => map(r, "org"))
    ];
    if (em_risco) krs = krs.filter((k) => k.status === "active" && k.progresso_pct < 70);
    return jsonResult({
      unidade: scope.buName,
      ciclo: chosenCycle?.name ?? null,
      total: krs.length,
      key_results: krs
    });
  }
});

// src/lib/mcp/tools/list-checkins.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z8 } from "npm:zod@^3.25.76";
var list_checkins_default = defineTool9({
  name: "list_checkins",
  title: "Listar check-ins de KR",
  description: "Lista check-ins registrados nos KRs da unidade, com valor anterior e novo, confian\xE7a, bloqueios e coment\xE1rios. Permite filtrar por KR, pessoa, time e per\xEDodo.",
  inputSchema: {
    bu: buArg,
    kr_id: z8.string().optional(),
    pessoa: z8.string().optional().describe("Nome, e-mail ou id de quem registrou."),
    desde: z8.string().optional().describe("Data inicial (AAAA-MM-DD)."),
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, kr_id, pessoa, desde, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    let query = scope.supabase.from("okr_checkins").select(
      "id, kr_id, date, previous_value, current_value, confidence, blockers, comments, user_id, team_id, okr_team_key_results(title)"
    ).eq("bu_id", scope.buId).order("date", { ascending: false }).limit(clampLimit(limite, 50));
    if (kr_id) query = query.eq("kr_id", kr_id);
    if (desde) query = query.gte("date", desde);
    if (pessoa) {
      const person = await resolvePerson(scope, pessoa);
      query = query.eq("user_id", person.id);
    }
    const { data, error } = await query;
    assertNoError(error, "check-ins");
    return jsonResult({
      unidade: scope.buName,
      checkins: (data ?? []).map((c) => ({
        id: c.id,
        kr_id: c.kr_id,
        kr: (Array.isArray(c.okr_team_key_results) ? c.okr_team_key_results[0] : c.okr_team_key_results)?.title ?? null,
        data: c.date,
        de: c.previous_value,
        para: c.current_value,
        confianca: c.confidence,
        bloqueios: c.blockers,
        comentarios: c.comments,
        autor_id: c.user_id
      }))
    });
  }
});

// src/lib/mcp/tools/list-initiatives.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z9 } from "npm:zod@^3.25.76";
var list_initiatives_default = defineTool10({
  name: "list_initiatives",
  title: "Listar iniciativas de OKR",
  description: "Lista as iniciativas (a\xE7\xF5es) vinculadas aos KRs da unidade, com status, prioridade, progresso, respons\xE1vel e prazo. Use para ver o que est\xE1 bloqueado ou atrasado.",
  inputSchema: {
    bu: buArg,
    kr_id: z9.string().optional(),
    status: z9.enum(["planned", "in_progress", "blocked", "completed", "cancelled"]).optional(),
    busca: searchArg,
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, kr_id, status, busca, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    let query = scope.supabase.from("okr_initiatives").select(
      "id, name, description, status, priority, progress, start_date, expected_end_date, owner_user_id, kr_id, contributors, okr_team_key_results(title)"
    ).eq("bu_id", scope.buId).is("deleted_at", null).order("expected_end_date", { ascending: true }).limit(clampLimit(limite, 100));
    if (kr_id) query = query.eq("kr_id", kr_id);
    if (status) query = query.eq("status", status);
    if (busca) query = query.ilike("name", `%${busca}%`);
    const { data, error } = await query;
    assertNoError(error, "iniciativas");
    return jsonResult({
      unidade: scope.buName,
      iniciativas: (data ?? []).map((i) => ({
        id: i.id,
        nome: i.name,
        descricao: i.description,
        status: i.status,
        prioridade: i.priority,
        progresso_pct: i.progress,
        inicio: i.start_date,
        prazo: i.expected_end_date,
        responsavel_id: i.owner_user_id,
        kr_id: i.kr_id,
        kr: (Array.isArray(i.okr_team_key_results) ? i.okr_team_key_results[0] : i.okr_team_key_results)?.title ?? null
      }))
    });
  }
});

// src/lib/mcp/tools/list-kpis.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z10 } from "npm:zod@^3.25.76";

// src/modules/okrs/utils/kpiVariations.ts
function orientedDeltaPct(deltaPct, direction) {
  if (deltaPct == null) return null;
  if (direction === "down") return -deltaPct;
  return deltaPct;
}

// src/lib/colors.ts
var KPI_RAG_STATUS_STYLES = {
  on_track: {
    label: "On Track",
    text: "text-status-green-muted-foreground",
    bg: "bg-status-green-muted",
    progress: "bg-status-green"
  },
  at_risk: {
    label: "Em Risco",
    text: "text-status-yellow-muted-foreground",
    bg: "bg-status-yellow-muted",
    progress: "bg-status-yellow"
  },
  off_track: {
    label: "Off Track",
    text: "text-status-red-muted-foreground",
    bg: "bg-status-red-muted",
    progress: "bg-status-red"
  },
  no_data: {
    label: "Sem Dados",
    text: "text-muted-foreground",
    bg: "bg-muted",
    progress: "bg-muted-foreground"
  }
};

// src/modules/kpis/types.ts
var KPI_TREND_STABLE_BAND_PCT = 2;
var RAG_STATUS_CONFIG = {
  on_track: { label: KPI_RAG_STATUS_STYLES.on_track.label, color: KPI_RAG_STATUS_STYLES.on_track.text, bgColor: KPI_RAG_STATUS_STYLES.on_track.bg },
  at_risk: { label: KPI_RAG_STATUS_STYLES.at_risk.label, color: KPI_RAG_STATUS_STYLES.at_risk.text, bgColor: KPI_RAG_STATUS_STYLES.at_risk.bg },
  off_track: { label: KPI_RAG_STATUS_STYLES.off_track.label, color: KPI_RAG_STATUS_STYLES.off_track.text, bgColor: KPI_RAG_STATUS_STYLES.off_track.bg },
  no_data: { label: KPI_RAG_STATUS_STYLES.no_data.label, color: KPI_RAG_STATUS_STYLES.no_data.text, bgColor: KPI_RAG_STATUS_STYLES.no_data.bg }
};

// src/modules/kpis/utils/trendClassification.ts
function classifyOriented(rawDeltaPct, direction, bandPct) {
  const oriented = orientedDeltaPct(rawDeltaPct, direction === "down" ? "down" : "up");
  if (oriented == null) return null;
  const band = Math.abs(bandPct);
  if (Math.abs(oriented) <= band) return "stable";
  return oriented > 0 ? "growth" : "decline";
}
function classifyKpiTrendSeries(series, direction, options = {}) {
  const bandPct = options.bandPct ?? KPI_TREND_STABLE_BAND_PCT;
  const minPoints = options.minPoints ?? 3;
  const points = (series ?? []).filter((p) => p && typeof p.value === "number" && Number.isFinite(p.value)).slice().sort((a, b) => a.reference_date.localeCompare(b.reference_date));
  if (points.length < 2) return null;
  const n = points.length;
  const first = points[0];
  const last = points[n - 1];
  let rawDeltaPct;
  if (n >= minPoints) {
    const meanX = (n - 1) / 2;
    const meanY = points.reduce((acc, p) => acc + p.value, 0) / n;
    let num = 0;
    let den = 0;
    points.forEach((p, i) => {
      num += (i - meanX) * (p.value - meanY);
      den += (i - meanX) ** 2;
    });
    if (den === 0 || meanY === 0) return null;
    const slope = num / den;
    const totalChange = slope * (n - 1);
    rawDeltaPct = totalChange / Math.abs(meanY) * 100;
  } else {
    if (first.value === 0) return null;
    rawDeltaPct = (last.value - first.value) / Math.abs(first.value) * 100;
  }
  const trend = classifyOriented(rawDeltaPct, direction, bandPct);
  if (trend == null) return null;
  const oriented = orientedDeltaPct(rawDeltaPct, direction === "down" ? "down" : "up") ?? 0;
  return {
    trend,
    orientedPct: oriented,
    points: n,
    firstDate: first.reference_date,
    lastDate: last.reference_date
  };
}

// src/lib/mcp/tools/list-kpis.ts
var TREND_LABEL = {
  growth: "crescimento",
  stable: "estabilidade",
  decline: "queda"
};
var list_kpis_default = defineTool11({
  name: "list_kpis",
  title: "Listar KPIs e m\xE9tricas",
  description: "Lista os KPIs e m\xE9tricas da unidade com meta, orienta\xE7\xE3o, frequ\xEAncia, \xFAltimo valor consolidado, farol e tend\xEAncia (crescimento, estabilidade ou queda) calculada sobre a s\xE9rie consolidada.",
  inputSchema: {
    bu: buArg,
    categoria: z10.enum(["financeiro", "growth", "cs", "produto", "operacoes", "pessoas"]).optional(),
    tipo: z10.enum(["kpi", "metric"]).optional(),
    janela_meses: z10.number().int().optional().describe("Janela para a tend\xEAncia: 3, 6 ou 12 meses (padr\xE3o 6)."),
    busca: searchArg,
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, categoria, tipo, janela_meses, busca, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    const window = [3, 6, 12].includes(janela_meses ?? 6) ? janela_meses ?? 6 : 6;
    let query = scope.supabase.from("kpi_metrics").select(
      "id, name, description, category, indicator_type, unit, direction, target_value, status, lifecycle_status, scope, frequency, consolidation_frequency, update_frequency, owner_user_id, team_id, area_id"
    ).eq("bu_id", scope.buId).is("deleted_at", null).eq("status", "active").order("name").limit(clampLimit(limite, 100));
    if (categoria) query = query.eq("category", categoria);
    if (tipo) query = query.eq("indicator_type", tipo);
    if (busca) query = query.ilike("name", `%${busca}%`);
    const { data: metrics, error } = await query;
    assertNoError(error, "KPIs");
    const ids = (metrics ?? []).map((m) => m.id);
    const since = /* @__PURE__ */ new Date();
    since.setMonth(since.getMonth() - window - 1);
    const { data: values, error: valuesError } = ids.length ? await scope.supabase.from("kpi_values").select("kpi_id, value, reference_date, input_type, rag_status, period_label").in("kpi_id", ids).gte("reference_date", since.toISOString().slice(0, 10)).order("reference_date", { ascending: false }).limit(1200) : { data: [], error: null };
    assertNoError(valuesError, "valores de KPI");
    const byKpi = /* @__PURE__ */ new Map();
    for (const v of values ?? []) {
      const list = byKpi.get(v.kpi_id) ?? [];
      list.push(v);
      byKpi.set(v.kpi_id, list);
    }
    const kpis = (metrics ?? []).map((m) => {
      const all = byKpi.get(m.id) ?? [];
      const consolidated = all.filter((v) => v.input_type !== "partial");
      const latest = consolidated[0] ?? all[0] ?? null;
      const trend = classifyKpiTrendSeries(
        consolidated.map((v) => ({
          value: Number(v.value),
          reference_date: String(v.reference_date)
        })),
        m.direction ?? "up"
      );
      return {
        id: m.id,
        nome: m.name,
        descricao: m.description,
        categoria: m.category,
        tipo: m.indicator_type,
        unidade: m.unit,
        orientacao: m.direction,
        meta: m.target_value,
        frequencia: m.frequency ?? m.consolidation_frequency,
        escopo: m.scope,
        ciclo_de_vida: m.lifecycle_status,
        responsavel_id: m.owner_user_id,
        ultimo_valor: latest ? Number(latest.value) : null,
        ultimo_periodo: latest ? latest.period_label ?? latest.reference_date : null,
        farol: latest?.rag_status ?? null,
        tendencia: trend ? TREND_LABEL[trend.trend] : "sem dados suficientes",
        tendencia_pct: trend ? Math.round(trend.orientedPct * 10) / 10 : null,
        tendencia_pontos: trend?.points ?? consolidated.length
      };
    });
    return jsonResult({ unidade: scope.buName, janela_meses: window, total: kpis.length, kpis });
  }
});

// src/lib/mcp/tools/kpi-history.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z11 } from "npm:zod@^3.25.76";
var kpi_history_default = defineTool12({
  name: "kpi_history",
  title: "Hist\xF3rico de um KPI",
  description: "Retorna a s\xE9rie hist\xF3rica de um KPI da unidade (valores consolidados e parciais), com per\xEDodo, farol, origem e observa\xE7\xF5es.",
  inputSchema: {
    kpi: z11.string().describe("Nome ou id do KPI."),
    bu: buArg,
    desde: z11.string().optional().describe("Data inicial (AAAA-MM-DD)."),
    apenas_consolidados: z11.boolean().optional().describe("Padr\xE3o: falso (traz parciais tamb\xE9m)."),
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kpi, bu, desde, apenas_consolidados, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(kpi);
    let metricQuery = scope.supabase.from("kpi_metrics").select("id, name, unit, direction, target_value, frequency, consolidation_frequency").eq("bu_id", scope.buId).is("deleted_at", null).limit(5);
    metricQuery = isUuid ? metricQuery.eq("id", kpi) : metricQuery.ilike("name", `%${kpi}%`);
    const { data: metrics, error: metricError } = await metricQuery;
    assertNoError(metricError, "KPIs");
    const metric = metrics?.[0];
    if (!metric) return jsonResult({ aviso: `KPI "${kpi}" n\xE3o encontrado na unidade ${scope.buName}.` });
    let query = scope.supabase.from("kpi_values").select("value, reference_date, period_start, period_end, period_label, input_type, rag_status, source, notes").eq("kpi_id", metric.id).order("reference_date", { ascending: false }).limit(clampLimit(limite, 60, 200));
    if (desde) query = query.gte("reference_date", desde);
    if (apenas_consolidados) query = query.neq("input_type", "partial");
    const { data, error } = await query;
    assertNoError(error, "valores de KPI");
    return jsonResult({
      unidade: scope.buName,
      kpi: {
        id: metric.id,
        nome: metric.name,
        unidade_medida: metric.unit,
        orientacao: metric.direction,
        meta: metric.target_value,
        frequencia: metric.frequency ?? metric.consolidation_frequency
      },
      alternativas: (metrics ?? []).slice(1).map((m) => m.name),
      valores: data ?? []
    });
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z12 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool13({
  name: "list_projects",
  title: "Listar projetos",
  description: "Lista os projetos da unidade com respons\xE1vel, status, datas e marcos (com prazo e situa\xE7\xE3o de cada marco). Use para saber o andamento e o que est\xE1 atrasado.",
  inputSchema: {
    bu: buArg,
    status: z12.enum(["planned", "in_progress", "paused", "done", "cancelled"]).optional(),
    busca: searchArg,
    incluir_marcos: z12.boolean().optional().describe("Padr\xE3o: verdadeiro."),
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, status, busca, incluir_marcos, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    let query = scope.supabase.from("projects").select("id, name, description, status, owner_id, start_date, due_date, external_url").eq("bu_id", scope.buId).is("deleted_at", null).order("due_date", { ascending: true }).limit(clampLimit(limite, 100));
    if (status) query = query.eq("status", status);
    if (busca) query = query.ilike("name", `%${busca}%`);
    const { data: projects, error } = await query;
    assertNoError(error, "projetos");
    const ids = (projects ?? []).map((p) => p.id);
    const withMilestones = incluir_marcos !== false && ids.length > 0;
    const { data: milestones } = withMilestones ? await scope.supabase.from("project_milestones").select("id, project_id, name, status, start_date, due_date, owner_id, sort_order").in("project_id", ids).is("deleted_at", null).order("sort_order").limit(500) : { data: [] };
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    return jsonResult({
      unidade: scope.buName,
      projetos: (projects ?? []).map((p) => {
        const marcos = (milestones ?? []).filter((m) => m.project_id === p.id);
        return {
          id: p.id,
          nome: p.name,
          descricao: p.description,
          status: p.status,
          responsavel_id: p.owner_id,
          inicio: p.start_date,
          prazo: p.due_date,
          link: p.external_url,
          marcos_total: marcos.length,
          marcos_concluidos: marcos.filter((m) => m.status === "done").length,
          marcos_atrasados: marcos.filter(
            (m) => m.status !== "done" && m.due_date && String(m.due_date) < today
          ).length,
          marcos: withMilestones ? marcos.map((m) => ({
            id: m.id,
            nome: m.name,
            status: m.status,
            inicio: m.start_date,
            prazo: m.due_date,
            responsavel_id: m.owner_id
          })) : void 0
        };
      })
    });
  }
});

// src/lib/mcp/tools/list-tickets.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z13 } from "npm:zod@^3.25.76";
var list_tickets_default = defineTool14({
  name: "list_tickets",
  title: "Listar tickets",
  description: "Lista os tickets vis\xEDveis para o usu\xE1rio na unidade, com tipo, situa\xE7\xE3o, prazo, respons\xE1vel, categoria e empresa parceira. Respeita as regras de visibilidade do Next.",
  inputSchema: {
    bu: buArg,
    status: z13.enum(["waiting", "paused", "in_progress", "done", "discarded"]).optional(),
    tipo: z13.enum(["internal", "external"]).optional(),
    atrasados: z13.boolean().optional().describe("Somente tickets em aberto com prazo vencido."),
    busca: searchArg,
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, status, tipo, atrasados, busca, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    let query = scope.supabase.from("tickets").select(
      "id, title, type, status, expected_due_at, owner_user_id, created_by_user_id, visibility, external_company_id, category_id, subcategory_id, created_at, updated_at, ticket_categories(name), external_companies(name)"
    ).eq("bu_id", scope.buId).is("deleted_at", null).order("updated_at", { ascending: false }).limit(clampLimit(limite, 50));
    if (status) query = query.eq("status", status);
    if (tipo) query = query.eq("type", tipo);
    if (busca) query = query.ilike("title", `%${busca}%`);
    if (atrasados) {
      query = query.lt("expected_due_at", (/* @__PURE__ */ new Date()).toISOString()).in("status", ["waiting", "paused", "in_progress"]);
    }
    const { data, error } = await query;
    assertNoError(error, "tickets");
    return jsonResult({
      unidade: scope.buName,
      total: (data ?? []).length,
      tickets: (data ?? []).map((t) => ({
        id: t.id,
        titulo: t.title,
        tipo: t.type,
        status: t.status,
        prazo: t.expected_due_at,
        responsavel_id: t.owner_user_id,
        autor_id: t.created_by_user_id,
        visibilidade: t.visibility,
        categoria: (Array.isArray(t.ticket_categories) ? t.ticket_categories[0] : t.ticket_categories)?.name ?? null,
        empresa: (Array.isArray(t.external_companies) ? t.external_companies[0] : t.external_companies)?.name ?? null,
        criado_em: t.created_at,
        atualizado_em: t.updated_at
      }))
    });
  }
});

// src/lib/mcp/tools/get-ticket.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z14 } from "npm:zod@^3.25.76";
var get_ticket_default = defineTool15({
  name: "get_ticket",
  title: "Detalhar um ticket",
  description: "Retorna os dados de um ticket e o hist\xF3rico de mensagens da conversa, al\xE9m dos participantes. Respeita as regras de visibilidade do Next.",
  inputSchema: {
    ticket_id: z14.string().describe("Id do ticket."),
    bu: buArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticket_id, bu }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    const [ticketRes, messagesRes, participantsRes] = await Promise.all([
      scope.supabase.from("tickets").select(
        "id, title, type, status, expected_due_at, owner_user_id, created_by_user_id, visibility, external_company_id, created_at, updated_at"
      ).eq("id", ticket_id).is("deleted_at", null).maybeSingle(),
      scope.supabase.from("ticket_messages").select("id, author_type, author_user_id, author_contact_id, body_richtext, is_pinned, created_at, edited_at").eq("ticket_id", ticket_id).is("deleted_at", null).order("created_at", { ascending: true }).limit(200),
      scope.supabase.from("ticket_participants").select("participant_type, role, user_id, contact_id").eq("ticket_id", ticket_id).limit(100)
    ]);
    assertNoError(ticketRes.error, "o ticket");
    if (!ticketRes.data) {
      return jsonResult({ aviso: "Ticket n\xE3o encontrado ou sem permiss\xE3o de visualiza\xE7\xE3o." });
    }
    assertNoError(messagesRes.error, "as mensagens do ticket");
    return jsonResult({
      unidade: scope.buName,
      ticket: ticketRes.data,
      participantes: participantsRes.data ?? [],
      mensagens: messagesRes.data ?? []
    });
  }
});

// src/lib/mcp/tools/list-rituals.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z15 } from "npm:zod@^3.25.76";
var list_rituals_default = defineTool16({
  name: "list_rituals",
  title: "Listar ritos",
  description: "Lista as ocorr\xEAncias dos ritos da unidade (check-in, pr\xE9-weekly, weekly, pr\xE9-MBR, MBR, QBR) com data planejada, situa\xE7\xE3o e time, al\xE9m das cad\xEAncias configuradas.",
  inputSchema: {
    bu: buArg,
    tipo: z15.string().optional().describe("Tipo do rito (ex.: weekly, mbr, qbr, checkin)."),
    desde: z15.string().optional().describe("Data inicial (AAAA-MM-DD)."),
    ate: z15.string().optional().describe("Data final (AAAA-MM-DD)."),
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, tipo, desde, ate, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    let occurrences = scope.supabase.from("ritual_occurrences").select("id, wizard_type, team_id, planned_date, actual_date, status, notes, teams(name)").eq("bu_id", scope.buId).order("planned_date", { ascending: false }).limit(clampLimit(limite, 60));
    if (tipo) occurrences = occurrences.ilike("wizard_type", `%${tipo}%`);
    if (desde) occurrences = occurrences.gte("planned_date", desde);
    if (ate) occurrences = occurrences.lte("planned_date", ate);
    const [occRes, cadRes] = await Promise.all([
      occurrences,
      scope.supabase.from("ritual_cadences").select("id, wizard_type, team_id, frequency, day_of_week, day_of_month, is_active, responsible_profile_id").eq("bu_id", scope.buId).eq("is_active", true).limit(100)
    ]);
    assertNoError(occRes.error, "ritos");
    return jsonResult({
      unidade: scope.buName,
      ocorrencias: (occRes.data ?? []).map((o) => ({
        id: o.id,
        rito: o.wizard_type,
        time: (Array.isArray(o.teams) ? o.teams[0] : o.teams)?.name ?? null,
        data_planejada: o.planned_date,
        data_realizada: o.actual_date,
        status: o.status,
        observacoes: o.notes
      })),
      cadencias: cadRes.data ?? []
    });
  }
});

// src/lib/mcp/tools/list-assets.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z16 } from "npm:zod@^3.25.76";
var list_assets_default = defineTool17({
  name: "list_assets",
  title: "Listar ativos (patrim\xF4nio)",
  description: "Lista os ativos do invent\xE1rio da unidade com c\xF3digo interno, categoria, marca/modelo, situa\xE7\xE3o, quantidade e quem/onde est\xE1 no momento.",
  inputSchema: {
    bu: buArg,
    situacao: z16.enum(["available", "loaned", "maintenance", "written_off"]).optional(),
    busca: searchArg,
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, situacao, busca, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    let query = scope.supabase.from("asset_inventory").select(
      "id, internal_code, name, description, status, brand, model, serial_number, quantity_total, quantity_available, current_holder_type, current_user_id, current_location_id, assigned_at, last_moved_at, acquired_at, acquisition_value, asset_categories(name)"
    ).eq("bu_id", scope.buId).is("deleted_at", null).order("name").limit(clampLimit(limite, 100));
    if (situacao) query = query.eq("status", situacao);
    if (busca) {
      query = query.or(
        [`name.ilike.%${busca}%`, `internal_code.ilike.%${busca}%`, `serial_number.ilike.%${busca}%`].join(",")
      );
    }
    const { data, error } = await query;
    assertNoError(error, "ativos");
    return jsonResult({
      unidade: scope.buName,
      ativos: (data ?? []).map((a) => ({
        id: a.id,
        codigo: a.internal_code,
        nome: a.name,
        categoria: (Array.isArray(a.asset_categories) ? a.asset_categories[0] : a.asset_categories)?.name ?? null,
        situacao: a.status,
        marca: a.brand,
        modelo: a.model,
        numero_serie: a.serial_number,
        quantidade_total: a.quantity_total,
        quantidade_disponivel: a.quantity_available,
        posse: a.current_holder_type,
        com_pessoa_id: a.current_user_id,
        local_id: a.current_location_id,
        desde: a.assigned_at,
        ultima_movimentacao: a.last_moved_at,
        aquisicao: a.acquired_at,
        valor_aquisicao: a.acquisition_value
      }))
    });
  }
});

// src/lib/mcp/tools/list-assessments.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z17 } from "npm:zod@^3.25.76";
var list_assessments_default = defineTool18({
  name: "list_assessments",
  title: "Listar avalia\xE7\xF5es",
  description: "Lista as avalia\xE7\xF5es da unidade com situa\xE7\xE3o, janela de disponibilidade e um resumo das aplica\xE7\xF5es (respostas iniciadas, enviadas e nota objetiva m\xE9dia). N\xE3o retorna respostas individuais nem CPF.",
  inputSchema: {
    bu: buArg,
    status: z17.enum(["draft", "active", "archived"]).optional(),
    busca: searchArg,
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, status, busca, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    let query = scope.supabase.from("assessments").select("id, title, description, status, available_from, available_until, default_total_time_seconds, created_at").eq("bu_id", scope.buId).is("deleted_at", null).order("created_at", { ascending: false }).limit(clampLimit(limite, 50));
    if (status) query = query.eq("status", status);
    if (busca) query = query.ilike("title", `%${busca}%`);
    const { data: assessments, error } = await query;
    assertNoError(error, "avalia\xE7\xF5es");
    const ids = (assessments ?? []).map((a) => a.id);
    const { data: runs } = ids.length ? await scope.supabase.from("assessment_runs").select("assessment_id, status, objective_score, submitted_at").in("assessment_id", ids).is("deleted_at", null).limit(1e3) : { data: [] };
    return jsonResult({
      unidade: scope.buName,
      avaliacoes: (assessments ?? []).map((a) => {
        const mine = (runs ?? []).filter((r) => r.assessment_id === a.id);
        const submitted = mine.filter((r) => r.status === "submitted");
        const scores = submitted.map((r) => Number(r.objective_score)).filter((n) => Number.isFinite(n));
        return {
          id: a.id,
          titulo: a.title,
          descricao: a.description,
          status: a.status,
          disponivel_de: a.available_from,
          disponivel_ate: a.available_until,
          tempo_total_segundos: a.default_total_time_seconds,
          aplicacoes: mine.length,
          enviadas: submitted.length,
          nota_objetiva_media: scores.length ? Math.round(scores.reduce((s, n) => s + n, 0) / scores.length * 10) / 10 : null
        };
      })
    });
  }
});

// src/lib/mcp/tools/list-partners.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z18 } from "npm:zod@^3.25.76";
var list_partners_default = defineTool19({
  name: "list_partners",
  title: "Listar empresas parceiras",
  description: "Lista as empresas parceiras vinculadas \xE0 unidade, com raz\xE3o social, documento, situa\xE7\xE3o e os contatos externos de cada uma.",
  inputSchema: {
    bu: buArg,
    status: z18.enum(["active", "inactive"]).optional(),
    busca: searchArg,
    incluir_contatos: z18.boolean().optional().describe("Padr\xE3o: verdadeiro."),
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, status, busca, incluir_contatos, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    const { data: associations, error: assocError } = await scope.supabase.from("external_company_bu_associations").select("external_company_id").eq("bu_id", scope.buId).limit(500);
    assertNoError(assocError, "parceiros da unidade");
    const associated = (associations ?? []).map((a) => a.external_company_id);
    let query = scope.supabase.from("external_companies").select("id, name, legal_name, document, document_type, person_type, status, notes, created_at").is("deleted_at", null).order("name").limit(clampLimit(limite, 100));
    if (associated.length) query = query.in("id", associated);
    if (status) query = query.eq("status", status);
    if (busca) query = query.or([`name.ilike.%${busca}%`, `legal_name.ilike.%${busca}%`].join(","));
    const { data: companies, error } = await query;
    assertNoError(error, "empresas parceiras");
    const ids = (companies ?? []).map((c) => c.id);
    const wantContacts = incluir_contatos !== false && ids.length > 0;
    const { data: contacts } = wantContacts ? await scope.supabase.from("partner_contacts").select("id, external_company_id, name, email, phone, status, can_view_company_tickets, user_id").in("external_company_id", ids).is("deleted_at", null).limit(500) : { data: [] };
    return jsonResult({
      unidade: scope.buName,
      empresas: (companies ?? []).map((c) => ({
        id: c.id,
        nome: c.name,
        razao_social: c.legal_name,
        documento: c.document,
        tipo_documento: c.document_type,
        tipo_pessoa: c.person_type,
        status: c.status,
        observacoes: c.notes,
        contatos: wantContacts ? (contacts ?? []).filter((k) => k.external_company_id === c.id).map((k) => ({
          id: k.id,
          nome: k.name,
          email: k.email,
          telefone: k.phone,
          status: k.status,
          ve_tickets_da_empresa: k.can_view_company_tickets,
          tem_acesso: !!k.user_id
        })) : void 0
      }))
    });
  }
});

// src/lib/mcp/tools/list-analyses.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z19 } from "npm:zod@^3.25.76";
var list_analyses_default = defineTool20({
  name: "list_analyses",
  title: "Listar an\xE1lises e decis\xF5es",
  description: "Lista os relat\xF3rios de an\xE1lise da unidade (premissa, m\xF3dulos, per\xEDodo, resultado e a\xE7\xF5es sugeridas) e as decis\xF5es estrat\xE9gicas registradas neles.",
  inputSchema: {
    bu: buArg,
    status: z19.enum(["pending", "generating", "complete", "failed"]).optional(),
    incluir_resultado: z19.boolean().optional().describe("Se verdadeiro, inclui o texto completo do resultado (pode ser longo)."),
    busca: searchArg,
    limite: limitArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bu, status, incluir_resultado, busca, limite }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    let query = scope.supabase.from("analysis_reports").select(
      "id, title, premise, modules, scope, period, depth, status, suggested_actions, generated_at, created_at, result"
    ).eq("bu_id", scope.buId).is("deleted_at", null).order("created_at", { ascending: false }).limit(clampLimit(limite, 20, 100));
    if (status) query = query.eq("status", status);
    if (busca) query = query.ilike("title", `%${busca}%`);
    const { data: reports, error } = await query;
    assertNoError(error, "an\xE1lises");
    const ids = (reports ?? []).map((r) => r.id);
    const { data: decisions } = ids.length ? await scope.supabase.from("analysis_decisions").select("id, report_id, decisions, created_at").in("report_id", ids).is("deleted_at", null).limit(200) : { data: [] };
    return jsonResult({
      unidade: scope.buName,
      analises: (reports ?? []).map((r) => ({
        id: r.id,
        titulo: r.title,
        premissa: r.premise,
        modulos: r.modules,
        escopo: r.scope,
        periodo: r.period,
        profundidade: r.depth,
        status: r.status,
        acoes_sugeridas: r.suggested_actions,
        gerado_em: r.generated_at,
        resultado: incluir_resultado ? r.result : void 0,
        decisoes: (decisions ?? []).filter((d) => d.report_id === r.id).map((d) => d.decisions)
      }))
    });
  }
});

// src/lib/mcp/tools/search-next.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z20 } from "npm:zod@^3.25.76";
var search_next_default = defineTool21({
  name: "search_next",
  title: "Busca geral no Next",
  description: "Busca um termo em v\xE1rios m\xF3dulos ao mesmo tempo (pessoas, objetivos, KRs, KPIs, projetos, tickets, ativos e parceiros) e devolve os resultados agrupados por m\xF3dulo. Use quando n\xE3o souber onde o assunto est\xE1 registrado.",
  inputSchema: {
    termo: z20.string().min(2).describe("Texto a procurar."),
    bu: buArg
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ termo, bu }, ctx) => {
    const scope = await resolveScope(ctx, bu);
    const { supabase, buId } = scope;
    const like = `%${termo}%`;
    const [people, orgObj, teamObj, teamKr, kpis, projects, tickets, assets, partners] = await Promise.all([
      supabase.from("profiles").select("id, display_name, work_email, employment_status").eq("bu_id", buId).is("deleted_at", null).or([`display_name.ilike.${like}`, `work_email.ilike.${like}`, `email.ilike.${like}`].join(",")).limit(10),
      supabase.from("okr_org_objectives").select("id, title, status").eq("bu_id", buId).is("deleted_at", null).ilike("title", like).limit(10),
      supabase.from("okr_team_objectives").select("id, title, status, team_id").eq("bu_id", buId).is("deleted_at", null).ilike("title", like).limit(10),
      supabase.from("okr_team_key_results").select("id, title, status, current_value, target, unit").eq("bu_id", buId).is("deleted_at", null).ilike("title", like).limit(10),
      supabase.from("kpi_metrics").select("id, name, category, indicator_type").eq("bu_id", buId).is("deleted_at", null).ilike("name", like).limit(10),
      supabase.from("projects").select("id, name, status").eq("bu_id", buId).is("deleted_at", null).ilike("name", like).limit(10),
      supabase.from("tickets").select("id, title, status, type").eq("bu_id", buId).is("deleted_at", null).ilike("title", like).limit(10),
      supabase.from("asset_inventory").select("id, internal_code, name, status").eq("bu_id", buId).is("deleted_at", null).or([`name.ilike.${like}`, `internal_code.ilike.${like}`].join(",")).limit(10),
      supabase.from("external_companies").select("id, name, status").is("deleted_at", null).ilike("name", like).limit(10)
    ]);
    return jsonResult({
      unidade: scope.buName,
      termo,
      pessoas: people.data ?? [],
      objetivos_org: orgObj.data ?? [],
      objetivos_time: teamObj.data ?? [],
      key_results: teamKr.data ?? [],
      kpis: kpis.data ?? [],
      projetos: projects.data ?? [],
      tickets: tickets.data ?? [],
      ativos: assets.data ?? [],
      parceiros: partners.data ?? []
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "oiwnghihyqdsinouwmga";
var mcp_default = defineMcp({
  name: "next",
  title: "Next",
  version: "1.0.0",
  instructions: [
    "Ferramentas de consulta do Next, o hub de gest\xE3o da Jetimob.",
    "Todas as consultas respeitam as permiss\xF5es da pessoa conectada e ficam restritas \xE0s unidades de neg\xF3cio a que ela tem acesso.",
    "Comece por `whoami` quando n\xE3o souber a unidade. Use `search_next` quando n\xE3o souber em qual m\xF3dulo o assunto est\xE1 registrado.",
    "Performance de pessoas: `person_performance` (uma pessoa) e `team_performance` (time inteiro).",
    "OKRs: `list_cycles`, `list_objectives`, `list_key_results`, `list_checkins`, `list_initiatives`.",
    "Indicadores: `list_kpis` (com tend\xEAncia) e `kpi_history`.",
    "Demais m\xF3dulos: `list_projects`, `list_tickets`, `get_ticket`, `list_rituals`, `list_assets`, `list_assessments`, `list_partners`, `list_analyses`, `list_org_structure`, `list_people`.",
    "Nenhuma ferramenta escreve dados: registros s\xF3 podem ser criados ou alterados dentro do Next."
  ].join(" "),
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_people_default,
    person_performance_default,
    team_performance_default,
    list_org_structure_default,
    list_cycles_default,
    list_objectives_default,
    list_key_results_default,
    list_checkins_default,
    list_initiatives_default,
    list_kpis_default,
    kpi_history_default,
    list_projects_default,
    list_tickets_default,
    get_ticket_default,
    list_rituals_default,
    list_assets_default,
    list_assessments_default,
    list_partners_default,
    list_analyses_default,
    search_next_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
